// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, created_at, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    int64
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, password_hash)
VALUES ($1, $2)
ON CONFLICT (email) DO NOTHING
RETURNING id, email
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

type CreateUserRow struct {
	ID    int64
	Email string
}

// Queries for accounts and sessions (internal/auth). Times come from the caller's clock.
// No row when the email is taken (emails are case-insensitive).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, now pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const sessionUser = `-- name: SessionUser :one
SELECT u.id, u.email, s.created_at, s.expires_at
  FROM sessions s
  JOIN users u ON u.id = s.user_id
 WHERE s.token_hash = $1
   AND s.expires_at > $2
`

type SessionUserParams struct {
	TokenHash []byte
	Now       pgtype.Timestamptz
}

type SessionUserRow struct {
	ID        int64
	Email     string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

// The user a session belongs to, if it hasn't expired.
func (q *Queries) SessionUser(ctx context.Context, arg SessionUserParams) (SessionUserRow, error) {
	row := q.db.QueryRow(ctx, sessionUser, arg.TokenHash, arg.Now)
	var i SessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE users SET password_hash = $1 WHERE id = $2
`

type SetPasswordHashParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const setSessionExpiry = `-- name: SetSessionExpiry :exec
UPDATE sessions SET expires_at = $1 WHERE token_hash = $2
`

type SetSessionExpiryParams struct {
	ExpiresAt pgtype.Timestamptz
	TokenHash []byte
}

func (q *Queries) SetSessionExpiry(ctx context.Context, arg SetSessionExpiryParams) error {
	_, err := q.db.Exec(ctx, setSessionExpiry, arg.ExpiresAt, arg.TokenHash)
	return err
}

const userCredentials = `-- name: UserCredentials :one
SELECT id, email, password_hash FROM users WHERE email = $1
`

type UserCredentialsRow struct {
	ID           int64
	Email        string
	PasswordHash string
}

func (q *Queries) UserCredentials(ctx context.Context, email string) (UserCredentialsRow, error) {
	row := q.db.QueryRow(ctx, userCredentials, email)
	var i UserCredentialsRow
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash)
	return i, err
}
