// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package store

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertSets = `-- name: UpsertSets :batchexec

INSERT INTO sets (code, scryfall_id, name, set_type, released_at, icon_svg_uri, parent_set_code)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (code) DO UPDATE
   SET scryfall_id     = EXCLUDED.scryfall_id,
       name            = EXCLUDED.name,
       set_type        = EXCLUDED.set_type,
       released_at     = EXCLUDED.released_at,
       icon_svg_uri    = EXCLUDED.icon_svg_uri,
       parent_set_code = EXCLUDED.parent_set_code,
       updated_at      = now()
 WHERE (sets.scryfall_id, sets.name, sets.set_type, sets.released_at, sets.icon_svg_uri, sets.parent_set_code)
       IS DISTINCT FROM
       (EXCLUDED.scryfall_id, EXCLUDED.name, EXCLUDED.set_type, EXCLUDED.released_at, EXCLUDED.icon_svg_uri, EXCLUDED.parent_set_code)
`

type UpsertSetsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertSetsParams struct {
	Code          string
	ScryfallID    pgtype.UUID
	Name          string
	SetType       string
	ReleasedAt    pgtype.Date
	IconSvgUri    pgtype.Text
	ParentSetCode pgtype.Text
}

// Queries for the Scryfall import (internal/cards).
// Inserts a set, or updates it if anything about it changed. Sent as one batch for all sets.
func (q *Queries) UpsertSets(ctx context.Context, arg []UpsertSetsParams) *UpsertSetsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Code,
			a.ScryfallID,
			a.Name,
			a.SetType,
			a.ReleasedAt,
			a.IconSvgUri,
			a.ParentSetCode,
		}
		batch.Queue(upsertSets, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertSetsBatchResults{br, len(arg), false}
}

func (b *UpsertSetsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertSetsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
