// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const autocompleteNames = `-- name: AutocompleteNames :many
SELECT name
  FROM cards
 WHERE name ILIKE $1::text
   AND gone_since IS NULL
   AND layout <> ALL ($2::text[])
 GROUP BY name
 ORDER BY (name ILIKE $3::text) DESC,
          ((' ' || name) ILIKE $4::text) DESC,
          count(*) DESC,
          name
 LIMIT $5
`

type AutocompleteNamesParams struct {
	NamePattern       string
	ExtraLayouts      []string
	PrefixPattern     string
	WordPrefixPattern string
	RowLimit          int32
}

// Distinct names containing the pattern: names that start with it first, then ones with a
// word that does, then the rest; within each, cards with more printings (a rough measure
// of how well known they are) first.
func (q *Queries) AutocompleteNames(ctx context.Context, arg AutocompleteNamesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, autocompleteNames,
		arg.NamePattern,
		arg.ExtraLayouts,
		arg.PrefixPattern,
		arg.WordPrefixPattern,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cardPrintings = `-- name: CardPrintings :many
SELECT v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM card_listing v
 WHERE v.oracle_id = $1
 ORDER BY v.released_at DESC, v.set_code, length(v.collector_number), v.collector_number, v.id
 LIMIT $3 OFFSET $2
`

type CardPrintingsParams struct {
	OracleID  pgtype.UUID
	RowOffset int32
	RowLimit  int32
}

type CardPrintingsRow struct {
	CardListing CardListing
}

// Every printing of the card with this oracle id, newest first, gone ones included (a
// collection may hold them).
func (q *Queries) CardPrintings(ctx context.Context, arg CardPrintingsParams) ([]CardPrintingsRow, error) {
	rows, err := q.db.Query(ctx, cardPrintings, arg.OracleID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardPrintingsRow
	for rows.Next() {
		var i CardPrintingsRow
		if err := rows.Scan(
			&i.CardListing.ID,
			&i.CardListing.OracleID,
			&i.CardListing.Name,
			&i.CardListing.Lang,
			&i.CardListing.SetCode,
			&i.CardListing.CollectorNumber,
			&i.CardListing.Rarity,
			&i.CardListing.Layout,
			&i.CardListing.ManaCost,
			&i.CardListing.Cmc,
			&i.CardListing.TypeLine,
			&i.CardListing.OracleText,
			&i.CardListing.Colors,
			&i.CardListing.ColorIdentity,
			&i.CardListing.Finishes,
			&i.CardListing.Images,
			&i.CardListing.Faces,
			&i.CardListing.PriceEur,
			&i.CardListing.PriceEurFoil,
			&i.CardListing.PriceUsd,
			&i.CardListing.PriceUsdFoil,
			&i.CardListing.PriceUsdEtched,
			&i.CardListing.CardmarketUrl,
			&i.CardListing.ReleasedAt,
			&i.CardListing.GoneSince,
			&i.CardListing.SetName,
			&i.CardListing.SetIconSvgUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCard = `-- name: GetCard :one
SELECT v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM card_listing v
 WHERE v.id = $1
`

type GetCardRow struct {
	CardListing CardListing
}

func (q *Queries) GetCard(ctx context.Context, id pgtype.UUID) (GetCardRow, error) {
	row := q.db.QueryRow(ctx, getCard, id)
	var i GetCardRow
	err := row.Scan(
		&i.CardListing.ID,
		&i.CardListing.OracleID,
		&i.CardListing.Name,
		&i.CardListing.Lang,
		&i.CardListing.SetCode,
		&i.CardListing.CollectorNumber,
		&i.CardListing.Rarity,
		&i.CardListing.Layout,
		&i.CardListing.ManaCost,
		&i.CardListing.Cmc,
		&i.CardListing.TypeLine,
		&i.CardListing.OracleText,
		&i.CardListing.Colors,
		&i.CardListing.ColorIdentity,
		&i.CardListing.Finishes,
		&i.CardListing.Images,
		&i.CardListing.Faces,
		&i.CardListing.PriceEur,
		&i.CardListing.PriceEurFoil,
		&i.CardListing.PriceUsd,
		&i.CardListing.PriceUsdFoil,
		&i.CardListing.PriceUsdEtched,
		&i.CardListing.CardmarketUrl,
		&i.CardListing.ReleasedAt,
		&i.CardListing.GoneSince,
		&i.CardListing.SetName,
		&i.CardListing.SetIconSvgUri,
	)
	return i, err
}

const searchCardsByName = `-- name: SearchCardsByName :many

SELECT v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM card_listing v
 WHERE v.id = ANY (
       SELECT DISTINCT ON (c.oracle_id) c.id
         FROM cards c
        WHERE c.name ILIKE $1::text
          AND c.name ILIKE ALL ($2::text[])
          AND c.gone_since IS NULL
          AND ($3::boolean OR c.layout <> ALL ($4::text[]))
          AND ($5::text IS NULL OR c.set_code = $5::text)
          AND ($6::text IS NULL OR c.rarity = $6::text)
          AND c.type_line ILIKE ALL ($7::text[])
          AND c.colors @> $8::text[]
          AND (NOT $9::boolean OR c.colors = '{}')
        ORDER BY c.oracle_id, (c.lang = 'en') DESC, c.released_at DESC, c.set_code, c.collector_number)
 -- The exact name first, then names that start with it.
 ORDER BY (lower(v.name) = lower($10::text)) DESC, (v.name ILIKE $11::text) DESC, v.name, v.oracle_id
 LIMIT $13 OFFSET $12
`

type SearchCardsByNameParams struct {
	NamePattern      string
	MoreNamePatterns []string
	IncludeExtras    bool
	ExtraLayouts     []string
	SetCode          pgtype.Text
	Rarity           pgtype.Text
	TypePatterns     []string
	Colors           []string
	Colorless        bool
	ExactName        string
	PrefixPattern    string
	RowOffset        int32
	RowLimit         int32
}

type SearchCardsByNameRow struct {
	CardListing CardListing
}

// Queries for the card API (internal/cards search.go). Patterns are ILIKE patterns built there, with the user's % _ \ escaped.
// One printing per card (oracle_id) whose name matches: an English one if there is, the
// newest. Name searches and set browsing are separate queries, each led by a condition its
// index can serve (the name's trigram index; the set's index): a combined "pattern is null
// or name matches" would leave a cached generic plan unable to use either.
func (q *Queries) SearchCardsByName(ctx context.Context, arg SearchCardsByNameParams) ([]SearchCardsByNameRow, error) {
	rows, err := q.db.Query(ctx, searchCardsByName,
		arg.NamePattern,
		arg.MoreNamePatterns,
		arg.IncludeExtras,
		arg.ExtraLayouts,
		arg.SetCode,
		arg.Rarity,
		arg.TypePatterns,
		arg.Colors,
		arg.Colorless,
		arg.ExactName,
		arg.PrefixPattern,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCardsByNameRow
	for rows.Next() {
		var i SearchCardsByNameRow
		if err := rows.Scan(
			&i.CardListing.ID,
			&i.CardListing.OracleID,
			&i.CardListing.Name,
			&i.CardListing.Lang,
			&i.CardListing.SetCode,
			&i.CardListing.CollectorNumber,
			&i.CardListing.Rarity,
			&i.CardListing.Layout,
			&i.CardListing.ManaCost,
			&i.CardListing.Cmc,
			&i.CardListing.TypeLine,
			&i.CardListing.OracleText,
			&i.CardListing.Colors,
			&i.CardListing.ColorIdentity,
			&i.CardListing.Finishes,
			&i.CardListing.Images,
			&i.CardListing.Faces,
			&i.CardListing.PriceEur,
			&i.CardListing.PriceEurFoil,
			&i.CardListing.PriceUsd,
			&i.CardListing.PriceUsdFoil,
			&i.CardListing.PriceUsdEtched,
			&i.CardListing.CardmarketUrl,
			&i.CardListing.ReleasedAt,
			&i.CardListing.GoneSince,
			&i.CardListing.SetName,
			&i.CardListing.SetIconSvgUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCardsInSet = `-- name: SearchCardsInSet :many
SELECT v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM card_listing v
 WHERE v.id = ANY (
       SELECT DISTINCT ON (c.oracle_id) c.id
         FROM cards c
        WHERE c.set_code = $1::text
          AND c.gone_since IS NULL
          AND ($2::boolean OR c.layout <> ALL ($3::text[]))
          AND ($4::text IS NULL OR c.rarity = $4::text)
          AND c.type_line ILIKE ALL ($5::text[])
          AND c.colors @> $6::text[]
          AND (NOT $7::boolean OR c.colors = '{}')
        ORDER BY c.oracle_id, (c.lang = 'en') DESC, c.released_at DESC, c.collector_number)
 ORDER BY v.name, v.oracle_id
 LIMIT $9 OFFSET $8
`

type SearchCardsInSetParams struct {
	SetCode       string
	IncludeExtras bool
	ExtraLayouts  []string
	Rarity        pgtype.Text
	TypePatterns  []string
	Colors        []string
	Colorless     bool
	RowOffset     int32
	RowLimit      int32
}

type SearchCardsInSetRow struct {
	CardListing CardListing
}

func (q *Queries) SearchCardsInSet(ctx context.Context, arg SearchCardsInSetParams) ([]SearchCardsInSetRow, error) {
	rows, err := q.db.Query(ctx, searchCardsInSet,
		arg.SetCode,
		arg.IncludeExtras,
		arg.ExtraLayouts,
		arg.Rarity,
		arg.TypePatterns,
		arg.Colors,
		arg.Colorless,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCardsInSetRow
	for rows.Next() {
		var i SearchCardsInSetRow
		if err := rows.Scan(
			&i.CardListing.ID,
			&i.CardListing.OracleID,
			&i.CardListing.Name,
			&i.CardListing.Lang,
			&i.CardListing.SetCode,
			&i.CardListing.CollectorNumber,
			&i.CardListing.Rarity,
			&i.CardListing.Layout,
			&i.CardListing.ManaCost,
			&i.CardListing.Cmc,
			&i.CardListing.TypeLine,
			&i.CardListing.OracleText,
			&i.CardListing.Colors,
			&i.CardListing.ColorIdentity,
			&i.CardListing.Finishes,
			&i.CardListing.Images,
			&i.CardListing.Faces,
			&i.CardListing.PriceEur,
			&i.CardListing.PriceEurFoil,
			&i.CardListing.PriceUsd,
			&i.CardListing.PriceUsdFoil,
			&i.CardListing.PriceUsdEtched,
			&i.CardListing.CardmarketUrl,
			&i.CardListing.ReleasedAt,
			&i.CardListing.GoneSince,
			&i.CardListing.SetName,
			&i.CardListing.SetIconSvgUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
