// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const autocompleteNames = `-- name: AutocompleteNames :many
SELECT name
  FROM cards
 WHERE name ILIKE $1::text
   AND gone_since IS NULL
   AND layout <> ALL ($2::text[])
   AND NOT type_line ILIKE ANY ($3::text[])
 GROUP BY name
 ORDER BY (name ILIKE $4::text) DESC,
          ((' ' || name) ILIKE $5::text) DESC,
          count(*) DESC,
          name
 LIMIT $6
`

type AutocompleteNamesParams struct {
	NamePattern       string
	ExtraLayouts      []string
	ExtraTypes        []string
	PrefixPattern     string
	WordPrefixPattern string
	RowLimit          int32
}

// Distinct names containing the pattern: names that start with it first, then ones with a
// word that does, then the rest; within each, cards with more printings (a rough measure
// of how well known they are) first.
func (q *Queries) AutocompleteNames(ctx context.Context, arg AutocompleteNamesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, autocompleteNames,
		arg.NamePattern,
		arg.ExtraLayouts,
		arg.ExtraTypes,
		arg.PrefixPattern,
		arg.WordPrefixPattern,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cardOracleID = `-- name: CardOracleID :one
SELECT oracle_id FROM cards WHERE id = $1
`

func (q *Queries) CardOracleID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, cardOracleID, id)
	var oracle_id pgtype.UUID
	err := row.Scan(&oracle_id)
	return oracle_id, err
}

const cardPrintings = `-- name: CardPrintings :many
SELECT v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM card_listing v
 WHERE v.oracle_id = $1
 ORDER BY v.released_at DESC, v.set_code, length(v.collector_number), v.collector_number, v.id
 LIMIT $3 OFFSET $2
`

type CardPrintingsParams struct {
	OracleID  pgtype.UUID
	RowOffset int32
	RowLimit  int32
}

type CardPrintingsRow struct {
	CardListing CardListing
}

// Every printing of the card with this oracle id, newest first, gone ones included (a
// collection may hold them).
func (q *Queries) CardPrintings(ctx context.Context, arg CardPrintingsParams) ([]CardPrintingsRow, error) {
	rows, err := q.db.Query(ctx, cardPrintings, arg.OracleID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardPrintingsRow
	for rows.Next() {
		var i CardPrintingsRow
		if err := rows.Scan(
			&i.CardListing.ID,
			&i.CardListing.OracleID,
			&i.CardListing.Name,
			&i.CardListing.Lang,
			&i.CardListing.SetCode,
			&i.CardListing.CollectorNumber,
			&i.CardListing.Rarity,
			&i.CardListing.Layout,
			&i.CardListing.ManaCost,
			&i.CardListing.Cmc,
			&i.CardListing.TypeLine,
			&i.CardListing.OracleText,
			&i.CardListing.Colors,
			&i.CardListing.ColorIdentity,
			&i.CardListing.Finishes,
			&i.CardListing.Images,
			&i.CardListing.Faces,
			&i.CardListing.PriceEur,
			&i.CardListing.PriceEurFoil,
			&i.CardListing.PriceUsd,
			&i.CardListing.PriceUsdFoil,
			&i.CardListing.PriceUsdEtched,
			&i.CardListing.CardmarketUrl,
			&i.CardListing.ReleasedAt,
			&i.CardListing.GoneSince,
			&i.CardListing.SetName,
			&i.CardListing.SetIconSvgUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCard = `-- name: GetCard :one
SELECT v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM card_listing v
 WHERE v.id = $1
`

type GetCardRow struct {
	CardListing CardListing
}

func (q *Queries) GetCard(ctx context.Context, id pgtype.UUID) (GetCardRow, error) {
	row := q.db.QueryRow(ctx, getCard, id)
	var i GetCardRow
	err := row.Scan(
		&i.CardListing.ID,
		&i.CardListing.OracleID,
		&i.CardListing.Name,
		&i.CardListing.Lang,
		&i.CardListing.SetCode,
		&i.CardListing.CollectorNumber,
		&i.CardListing.Rarity,
		&i.CardListing.Layout,
		&i.CardListing.ManaCost,
		&i.CardListing.Cmc,
		&i.CardListing.TypeLine,
		&i.CardListing.OracleText,
		&i.CardListing.Colors,
		&i.CardListing.ColorIdentity,
		&i.CardListing.Finishes,
		&i.CardListing.Images,
		&i.CardListing.Faces,
		&i.CardListing.PriceEur,
		&i.CardListing.PriceEurFoil,
		&i.CardListing.PriceUsd,
		&i.CardListing.PriceUsdFoil,
		&i.CardListing.PriceUsdEtched,
		&i.CardListing.CardmarketUrl,
		&i.CardListing.ReleasedAt,
		&i.CardListing.GoneSince,
		&i.CardListing.SetName,
		&i.CardListing.SetIconSvgUri,
	)
	return i, err
}

const searchCardsByName = `-- name: SearchCardsByName :many

WITH picked AS (
    SELECT DISTINCT ON (c.oracle_id) c.id, c.name, c.oracle_id
      FROM cards c
      JOIN sets s ON s.code = c.set_code
     WHERE c.name ILIKE $1::text
       AND c.name ILIKE ALL ($2::text[])
       AND c.gone_since IS NULL
       AND ($3::boolean
            OR (c.layout <> ALL ($4::text[]) AND NOT c.type_line ILIKE ANY ($5::text[])))
       AND ($6::text IS NULL OR c.set_code = $6::text)
       AND ($7::text IS NULL OR c.rarity = $7::text)
       AND c.type_line ILIKE ALL ($8::text[])
       AND c.colors @> $9::text[]
       AND (NOT $10::boolean OR c.colors = '{}')
     ORDER BY c.oracle_id,
              (c.lang = 'en') DESC,
              (c.released_at <= current_date) DESC,
              (s.set_type = ANY ($11::text[])) DESC,
              c.released_at DESC, c.set_code, length(c.collector_number), c.collector_number, c.id
), page AS (
    -- Names that start with what was typed first (the exact name among them, as it's shortest).
    SELECT p.id, p.name, p.oracle_id, (p.name ILIKE $12::text) AS starts_with
      FROM picked p
     ORDER BY starts_with DESC, p.name, p.oracle_id
     LIMIT $14 OFFSET $13
)
SELECT v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM page
  JOIN card_listing v ON v.id = page.id
 ORDER BY page.starts_with DESC, page.name, page.oracle_id
`

type SearchCardsByNameParams struct {
	LeadPattern     string
	NamePatterns    []string
	IncludeExtras   bool
	ExtraLayouts    []string
	ExtraTypes      []string
	SetCode         pgtype.Text
	Rarity          pgtype.Text
	TypePatterns    []string
	Colors          []string
	Colorless       bool
	RegularSetTypes []string
	PrefixPattern   string
	RowOffset       int32
	RowLimit        int32
}

type SearchCardsByNameRow struct {
	CardListing CardListing
}

// Queries for the card API (internal/cards search.go). Patterns are ILIKE patterns built there, with the user's % _ \ escaped.
// A page of cards whose name matches, one printing each (see search.go for which). The
// search is led by a name pattern the trigram index can serve; set browsing is a separate
// query led by the set's index. The ranking and paging are done on narrow rows, and only
// the page's cards are then read in full.
func (q *Queries) SearchCardsByName(ctx context.Context, arg SearchCardsByNameParams) ([]SearchCardsByNameRow, error) {
	rows, err := q.db.Query(ctx, searchCardsByName,
		arg.LeadPattern,
		arg.NamePatterns,
		arg.IncludeExtras,
		arg.ExtraLayouts,
		arg.ExtraTypes,
		arg.SetCode,
		arg.Rarity,
		arg.TypePatterns,
		arg.Colors,
		arg.Colorless,
		arg.RegularSetTypes,
		arg.PrefixPattern,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCardsByNameRow
	for rows.Next() {
		var i SearchCardsByNameRow
		if err := rows.Scan(
			&i.CardListing.ID,
			&i.CardListing.OracleID,
			&i.CardListing.Name,
			&i.CardListing.Lang,
			&i.CardListing.SetCode,
			&i.CardListing.CollectorNumber,
			&i.CardListing.Rarity,
			&i.CardListing.Layout,
			&i.CardListing.ManaCost,
			&i.CardListing.Cmc,
			&i.CardListing.TypeLine,
			&i.CardListing.OracleText,
			&i.CardListing.Colors,
			&i.CardListing.ColorIdentity,
			&i.CardListing.Finishes,
			&i.CardListing.Images,
			&i.CardListing.Faces,
			&i.CardListing.PriceEur,
			&i.CardListing.PriceEurFoil,
			&i.CardListing.PriceUsd,
			&i.CardListing.PriceUsdFoil,
			&i.CardListing.PriceUsdEtched,
			&i.CardListing.CardmarketUrl,
			&i.CardListing.ReleasedAt,
			&i.CardListing.GoneSince,
			&i.CardListing.SetName,
			&i.CardListing.SetIconSvgUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCardsInSet = `-- name: SearchCardsInSet :many
WITH picked AS (
    SELECT DISTINCT ON (c.oracle_id) c.id, c.name, c.oracle_id
      FROM cards c
     WHERE c.set_code = $1::text
       AND c.name ILIKE ALL ($2::text[])
       AND c.gone_since IS NULL
       AND ($3::boolean
            OR (c.layout <> ALL ($4::text[]) AND NOT c.type_line ILIKE ANY ($5::text[])))
       AND ($6::text IS NULL OR c.rarity = $6::text)
       AND c.type_line ILIKE ALL ($7::text[])
       AND c.colors @> $8::text[]
       AND (NOT $9::boolean OR c.colors = '{}')
     ORDER BY c.oracle_id,
              (c.lang = 'en') DESC,
              (c.released_at <= current_date) DESC,
              c.released_at DESC, length(c.collector_number), c.collector_number, c.id
), page AS (
    SELECT p.id, p.name, p.oracle_id
      FROM picked p
     ORDER BY p.name, p.oracle_id
     LIMIT $11 OFFSET $10
)
SELECT v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM page
  JOIN card_listing v ON v.id = page.id
 ORDER BY page.name, page.oracle_id
`

type SearchCardsInSetParams struct {
	SetCode       string
	NamePatterns  []string
	IncludeExtras bool
	ExtraLayouts  []string
	ExtraTypes    []string
	Rarity        pgtype.Text
	TypePatterns  []string
	Colors        []string
	Colorless     bool
	RowOffset     int32
	RowLimit      int32
}

type SearchCardsInSetRow struct {
	CardListing CardListing
}

// A page of the cards in a set, by name, one printing each (the set's own), optionally
// narrowed by name words too short to lead a name search.
func (q *Queries) SearchCardsInSet(ctx context.Context, arg SearchCardsInSetParams) ([]SearchCardsInSetRow, error) {
	rows, err := q.db.Query(ctx, searchCardsInSet,
		arg.SetCode,
		arg.NamePatterns,
		arg.IncludeExtras,
		arg.ExtraLayouts,
		arg.ExtraTypes,
		arg.Rarity,
		arg.TypePatterns,
		arg.Colors,
		arg.Colorless,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCardsInSetRow
	for rows.Next() {
		var i SearchCardsInSetRow
		if err := rows.Scan(
			&i.CardListing.ID,
			&i.CardListing.OracleID,
			&i.CardListing.Name,
			&i.CardListing.Lang,
			&i.CardListing.SetCode,
			&i.CardListing.CollectorNumber,
			&i.CardListing.Rarity,
			&i.CardListing.Layout,
			&i.CardListing.ManaCost,
			&i.CardListing.Cmc,
			&i.CardListing.TypeLine,
			&i.CardListing.OracleText,
			&i.CardListing.Colors,
			&i.CardListing.ColorIdentity,
			&i.CardListing.Finishes,
			&i.CardListing.Images,
			&i.CardListing.Faces,
			&i.CardListing.PriceEur,
			&i.CardListing.PriceEurFoil,
			&i.CardListing.PriceUsd,
			&i.CardListing.PriceUsdFoil,
			&i.CardListing.PriceUsdEtched,
			&i.CardListing.CardmarketUrl,
			&i.CardListing.ReleasedAt,
			&i.CardListing.GoneSince,
			&i.CardListing.SetName,
			&i.CardListing.SetIconSvgUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
