// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collection.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addEntry = `-- name: AddEntry :one
INSERT INTO collection_entries AS e (user_id, card_id, quantity, finish, condition, language)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, card_id, finish, condition, language)
DO UPDATE SET quantity = e.quantity + excluded.quantity
        WHERE e.quantity + excluded.quantity <= 999
RETURNING e.id, (xmax = 0)::boolean AS created
`

type AddEntryParams struct {
	UserID    int64
	CardID    pgtype.UUID
	Quantity  int32
	Finish    string
	Condition string
	Language  string
}

type AddEntryRow struct {
	ID      int64
	Created bool
}

// Adds copies: a new entry, or more of one the user has with the same printing, finish,
// condition and language. No row when that would make more than 999 copies.
func (q *Queries) AddEntry(ctx context.Context, arg AddEntryParams) (AddEntryRow, error) {
	row := q.db.QueryRow(ctx, addEntry,
		arg.UserID,
		arg.CardID,
		arg.Quantity,
		arg.Finish,
		arg.Condition,
		arg.Language,
	)
	var i AddEntryRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}

const cardFinishes = `-- name: CardFinishes :one

SELECT finishes FROM cards WHERE id = $1
`

// Queries for the collection (internal/collection). Every one is for one user's entries:
// user_id is in every WHERE clause.
func (q *Queries) CardFinishes(ctx context.Context, id pgtype.UUID) ([]string, error) {
	row := q.db.QueryRow(ctx, cardFinishes, id)
	var finishes []string
	err := row.Scan(&finishes)
	return finishes, err
}

const deleteEntry = `-- name: DeleteEntry :execrows
DELETE FROM collection_entries WHERE user_id = $1 AND id = $2
`

type DeleteEntryParams struct {
	UserID int64
	ID     int64
}

func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEntry, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const entriesByAdded = `-- name: EntriesByAdded :many
SELECT e.id, e.quantity, e.finish, e.condition, e.language, e.added_at,
       unit_price_eur(e.finish, v.price_eur, v.price_eur_foil)::numeric AS unit_price,
       line_value(unit_price_eur(e.finish, v.price_eur, v.price_eur_foil), e.quantity)::numeric AS value,
       v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM collection_entries e
  JOIN card_listing v ON v.id = e.card_id
 WHERE e.user_id = $1
   AND card_group($2, v.set_code, v.color_identity, v.type_line, v.rarity, v.cmc) = $3
   AND ($4::bigint IS NULL
        OR (e.added_at, e.id) < ($5::timestamptz, $4::bigint))
 ORDER BY e.added_at DESC, e.id DESC
 LIMIT $6
`

type EntriesByAddedParams struct {
	UserID     int64
	GroupBy    string
	GroupKey   string
	AfterID    pgtype.Int8
	AfterAdded pgtype.Timestamptz
	RowLimit   int32
}

type EntriesByAddedRow struct {
	ID          int64
	Quantity    int32
	Finish      string
	Condition   string
	Language    string
	AddedAt     pgtype.Timestamptz
	UnitPrice   pgtype.Numeric
	Value       pgtype.Numeric
	CardListing CardListing
}

// Newest first.
func (q *Queries) EntriesByAdded(ctx context.Context, arg EntriesByAddedParams) ([]EntriesByAddedRow, error) {
	rows, err := q.db.Query(ctx, entriesByAdded,
		arg.UserID,
		arg.GroupBy,
		arg.GroupKey,
		arg.AfterID,
		arg.AfterAdded,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntriesByAddedRow
	for rows.Next() {
		var i EntriesByAddedRow
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.Finish,
			&i.Condition,
			&i.Language,
			&i.AddedAt,
			&i.UnitPrice,
			&i.Value,
			&i.CardListing.ID,
			&i.CardListing.OracleID,
			&i.CardListing.Name,
			&i.CardListing.Lang,
			&i.CardListing.SetCode,
			&i.CardListing.CollectorNumber,
			&i.CardListing.Rarity,
			&i.CardListing.Layout,
			&i.CardListing.ManaCost,
			&i.CardListing.Cmc,
			&i.CardListing.TypeLine,
			&i.CardListing.OracleText,
			&i.CardListing.Colors,
			&i.CardListing.ColorIdentity,
			&i.CardListing.Finishes,
			&i.CardListing.Images,
			&i.CardListing.Faces,
			&i.CardListing.PriceEur,
			&i.CardListing.PriceEurFoil,
			&i.CardListing.PriceUsd,
			&i.CardListing.PriceUsdFoil,
			&i.CardListing.PriceUsdEtched,
			&i.CardListing.CardmarketUrl,
			&i.CardListing.ReleasedAt,
			&i.CardListing.GoneSince,
			&i.CardListing.SetName,
			&i.CardListing.SetIconSvgUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesByCMC = `-- name: EntriesByCMC :many
SELECT e.id, e.quantity, e.finish, e.condition, e.language, e.added_at,
       unit_price_eur(e.finish, v.price_eur, v.price_eur_foil)::numeric AS unit_price,
       line_value(unit_price_eur(e.finish, v.price_eur, v.price_eur_foil), e.quantity)::numeric AS value,
       v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM collection_entries e
  JOIN card_listing v ON v.id = e.card_id
 WHERE e.user_id = $1
   AND card_group($2, v.set_code, v.color_identity, v.type_line, v.rarity, v.cmc) = $3
   AND ($4::bigint IS NULL
        OR (v.cmc, v.name, e.id) > ($5::numeric, $6::text, $4::bigint))
 ORDER BY v.cmc, v.name, e.id
 LIMIT $7
`

type EntriesByCMCParams struct {
	UserID    int64
	GroupBy   string
	GroupKey  string
	AfterID   pgtype.Int8
	AfterCmc  pgtype.Numeric
	AfterName pgtype.Text
	RowLimit  int32
}

type EntriesByCMCRow struct {
	ID          int64
	Quantity    int32
	Finish      string
	Condition   string
	Language    string
	AddedAt     pgtype.Timestamptz
	UnitPrice   pgtype.Numeric
	Value       pgtype.Numeric
	CardListing CardListing
}

func (q *Queries) EntriesByCMC(ctx context.Context, arg EntriesByCMCParams) ([]EntriesByCMCRow, error) {
	rows, err := q.db.Query(ctx, entriesByCMC,
		arg.UserID,
		arg.GroupBy,
		arg.GroupKey,
		arg.AfterID,
		arg.AfterCmc,
		arg.AfterName,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntriesByCMCRow
	for rows.Next() {
		var i EntriesByCMCRow
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.Finish,
			&i.Condition,
			&i.Language,
			&i.AddedAt,
			&i.UnitPrice,
			&i.Value,
			&i.CardListing.ID,
			&i.CardListing.OracleID,
			&i.CardListing.Name,
			&i.CardListing.Lang,
			&i.CardListing.SetCode,
			&i.CardListing.CollectorNumber,
			&i.CardListing.Rarity,
			&i.CardListing.Layout,
			&i.CardListing.ManaCost,
			&i.CardListing.Cmc,
			&i.CardListing.TypeLine,
			&i.CardListing.OracleText,
			&i.CardListing.Colors,
			&i.CardListing.ColorIdentity,
			&i.CardListing.Finishes,
			&i.CardListing.Images,
			&i.CardListing.Faces,
			&i.CardListing.PriceEur,
			&i.CardListing.PriceEurFoil,
			&i.CardListing.PriceUsd,
			&i.CardListing.PriceUsdFoil,
			&i.CardListing.PriceUsdEtched,
			&i.CardListing.CardmarketUrl,
			&i.CardListing.ReleasedAt,
			&i.CardListing.GoneSince,
			&i.CardListing.SetName,
			&i.CardListing.SetIconSvgUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesByName = `-- name: EntriesByName :many

SELECT e.id, e.quantity, e.finish, e.condition, e.language, e.added_at,
       unit_price_eur(e.finish, v.price_eur, v.price_eur_foil)::numeric AS unit_price,
       line_value(unit_price_eur(e.finish, v.price_eur, v.price_eur_foil), e.quantity)::numeric AS value,
       v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM collection_entries e
  JOIN card_listing v ON v.id = e.card_id
 WHERE e.user_id = $1
   AND card_group($2, v.set_code, v.color_identity, v.type_line, v.rarity, v.cmc) = $3
   AND ($4::bigint IS NULL OR (v.name, e.id) > ($5::text, $4::bigint))
 ORDER BY v.name, e.id
 LIMIT $6
`

type EntriesByNameParams struct {
	UserID    int64
	GroupBy   string
	GroupKey  string
	AfterID   pgtype.Int8
	AfterName pgtype.Text
	RowLimit  int32
}

type EntriesByNameRow struct {
	ID          int64
	Quantity    int32
	Finish      string
	Condition   string
	Language    string
	AddedAt     pgtype.Timestamptz
	UnitPrice   pgtype.Numeric
	Value       pgtype.Numeric
	CardListing CardListing
}

// A page of one group's entries, in one order. Each order is its own query, so each can
// page by keyset: the page after the row whose sort key is the cursor's. The group is the
// one card_group gives the key for; group_by 'none' is every entry.
func (q *Queries) EntriesByName(ctx context.Context, arg EntriesByNameParams) ([]EntriesByNameRow, error) {
	rows, err := q.db.Query(ctx, entriesByName,
		arg.UserID,
		arg.GroupBy,
		arg.GroupKey,
		arg.AfterID,
		arg.AfterName,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntriesByNameRow
	for rows.Next() {
		var i EntriesByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.Finish,
			&i.Condition,
			&i.Language,
			&i.AddedAt,
			&i.UnitPrice,
			&i.Value,
			&i.CardListing.ID,
			&i.CardListing.OracleID,
			&i.CardListing.Name,
			&i.CardListing.Lang,
			&i.CardListing.SetCode,
			&i.CardListing.CollectorNumber,
			&i.CardListing.Rarity,
			&i.CardListing.Layout,
			&i.CardListing.ManaCost,
			&i.CardListing.Cmc,
			&i.CardListing.TypeLine,
			&i.CardListing.OracleText,
			&i.CardListing.Colors,
			&i.CardListing.ColorIdentity,
			&i.CardListing.Finishes,
			&i.CardListing.Images,
			&i.CardListing.Faces,
			&i.CardListing.PriceEur,
			&i.CardListing.PriceEurFoil,
			&i.CardListing.PriceUsd,
			&i.CardListing.PriceUsdFoil,
			&i.CardListing.PriceUsdEtched,
			&i.CardListing.CardmarketUrl,
			&i.CardListing.ReleasedAt,
			&i.CardListing.GoneSince,
			&i.CardListing.SetName,
			&i.CardListing.SetIconSvgUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesByPrice = `-- name: EntriesByPrice :many
SELECT e.id, e.quantity, e.finish, e.condition, e.language, e.added_at,
       unit_price_eur(e.finish, v.price_eur, v.price_eur_foil)::numeric AS unit_price,
       line_value(unit_price_eur(e.finish, v.price_eur, v.price_eur_foil), e.quantity)::numeric AS value,
       v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM collection_entries e
  JOIN card_listing v ON v.id = e.card_id
 WHERE e.user_id = $1
   AND card_group($2, v.set_code, v.color_identity, v.type_line, v.rarity, v.cmc) = $3
   AND ($4::bigint IS NULL
        OR (unit_price_eur(e.finish, v.price_eur, v.price_eur_foil) IS NULL,
            -coalesce(unit_price_eur(e.finish, v.price_eur, v.price_eur_foil), 0), e.id)
         > ($5::boolean, -coalesce($6::numeric, 0), $4::bigint))
 ORDER BY unit_price_eur(e.finish, v.price_eur, v.price_eur_foil) IS NULL,
          -coalesce(unit_price_eur(e.finish, v.price_eur, v.price_eur_foil), 0), e.id
 LIMIT $7
`

type EntriesByPriceParams struct {
	UserID        int64
	GroupBy       string
	GroupKey      string
	AfterID       pgtype.Int8
	AfterUnpriced pgtype.Bool
	AfterPrice    pgtype.Numeric
	RowLimit      int32
}

type EntriesByPriceRow struct {
	ID          int64
	Quantity    int32
	Finish      string
	Condition   string
	Language    string
	AddedAt     pgtype.Timestamptz
	UnitPrice   pgtype.Numeric
	Value       pgtype.Numeric
	CardListing CardListing
}

// Most valuable copy first; those with no price last.
func (q *Queries) EntriesByPrice(ctx context.Context, arg EntriesByPriceParams) ([]EntriesByPriceRow, error) {
	rows, err := q.db.Query(ctx, entriesByPrice,
		arg.UserID,
		arg.GroupBy,
		arg.GroupKey,
		arg.AfterID,
		arg.AfterUnpriced,
		arg.AfterPrice,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntriesByPriceRow
	for rows.Next() {
		var i EntriesByPriceRow
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.Finish,
			&i.Condition,
			&i.Language,
			&i.AddedAt,
			&i.UnitPrice,
			&i.Value,
			&i.CardListing.ID,
			&i.CardListing.OracleID,
			&i.CardListing.Name,
			&i.CardListing.Lang,
			&i.CardListing.SetCode,
			&i.CardListing.CollectorNumber,
			&i.CardListing.Rarity,
			&i.CardListing.Layout,
			&i.CardListing.ManaCost,
			&i.CardListing.Cmc,
			&i.CardListing.TypeLine,
			&i.CardListing.OracleText,
			&i.CardListing.Colors,
			&i.CardListing.ColorIdentity,
			&i.CardListing.Finishes,
			&i.CardListing.Images,
			&i.CardListing.Faces,
			&i.CardListing.PriceEur,
			&i.CardListing.PriceEurFoil,
			&i.CardListing.PriceUsd,
			&i.CardListing.PriceUsdFoil,
			&i.CardListing.PriceUsdEtched,
			&i.CardListing.CardmarketUrl,
			&i.CardListing.ReleasedAt,
			&i.CardListing.GoneSince,
			&i.CardListing.SetName,
			&i.CardListing.SetIconSvgUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entryCard = `-- name: EntryCard :one

SELECT e.quantity, e.finish, e.condition, e.language, c.finishes
  FROM collection_entries e
  JOIN cards c ON c.id = e.card_id
 WHERE e.user_id = $1 AND e.id = $2
`

type EntryCardParams struct {
	UserID int64
	ID     int64
}

type EntryCardRow struct {
	Quantity  int32
	Finish    string
	Condition string
	Language  string
	Finishes  []string
}

// xmax is 0 for a row this statement inserted
// What an entry is, for checking a change to it.
func (q *Queries) EntryCard(ctx context.Context, arg EntryCardParams) (EntryCardRow, error) {
	row := q.db.QueryRow(ctx, entryCard, arg.UserID, arg.ID)
	var i EntryCardRow
	err := row.Scan(
		&i.Quantity,
		&i.Finish,
		&i.Condition,
		&i.Language,
		&i.Finishes,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT e.id, e.quantity, e.finish, e.condition, e.language, e.added_at,
       unit_price_eur(e.finish, v.price_eur, v.price_eur_foil)::numeric AS unit_price,
       line_value(unit_price_eur(e.finish, v.price_eur, v.price_eur_foil), e.quantity)::numeric AS value,
       v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM collection_entries e
  JOIN card_listing v ON v.id = e.card_id
 WHERE e.user_id = $1 AND e.id = $2
`

type GetEntryParams struct {
	UserID int64
	ID     int64
}

type GetEntryRow struct {
	ID          int64
	Quantity    int32
	Finish      string
	Condition   string
	Language    string
	AddedAt     pgtype.Timestamptz
	UnitPrice   pgtype.Numeric
	Value       pgtype.Numeric
	CardListing CardListing
}

func (q *Queries) GetEntry(ctx context.Context, arg GetEntryParams) (GetEntryRow, error) {
	row := q.db.QueryRow(ctx, getEntry, arg.UserID, arg.ID)
	var i GetEntryRow
	err := row.Scan(
		&i.ID,
		&i.Quantity,
		&i.Finish,
		&i.Condition,
		&i.Language,
		&i.AddedAt,
		&i.UnitPrice,
		&i.Value,
		&i.CardListing.ID,
		&i.CardListing.OracleID,
		&i.CardListing.Name,
		&i.CardListing.Lang,
		&i.CardListing.SetCode,
		&i.CardListing.CollectorNumber,
		&i.CardListing.Rarity,
		&i.CardListing.Layout,
		&i.CardListing.ManaCost,
		&i.CardListing.Cmc,
		&i.CardListing.TypeLine,
		&i.CardListing.OracleText,
		&i.CardListing.Colors,
		&i.CardListing.ColorIdentity,
		&i.CardListing.Finishes,
		&i.CardListing.Images,
		&i.CardListing.Faces,
		&i.CardListing.PriceEur,
		&i.CardListing.PriceEurFoil,
		&i.CardListing.PriceUsd,
		&i.CardListing.PriceUsdFoil,
		&i.CardListing.PriceUsdEtched,
		&i.CardListing.CardmarketUrl,
		&i.CardListing.ReleasedAt,
		&i.CardListing.GoneSince,
		&i.CardListing.SetName,
		&i.CardListing.SetIconSvgUri,
	)
	return i, err
}

const groupTotals = `-- name: GroupTotals :many
SELECT card_group($1, c.set_code, c.color_identity, c.type_line, c.rarity, c.cmc)::text AS key,
       count(*)::integer AS entry_count,
       sum(e.quantity)::integer AS card_count,
       coalesce(sum(line_value(unit_price_eur(e.finish, c.price_eur, c.price_eur_foil), e.quantity)), 0)::numeric AS value_eur,
       coalesce(sum(e.quantity) FILTER (WHERE unit_price_eur(e.finish, c.price_eur, c.price_eur_foil) IS NULL), 0)::integer AS unpriced_count
  FROM collection_entries e
  JOIN cards c ON c.id = e.card_id
 WHERE e.user_id = $2
 GROUP BY 1
`

type GroupTotalsParams struct {
	GroupBy string
	UserID  int64
}

type GroupTotalsRow struct {
	Key           string
	EntryCount    int32
	CardCount     int32
	ValueEur      pgtype.Numeric
	UnpricedCount int32
}

// The groups of the user's collection for one way of grouping, with their totals. Cards
// with no price are counted apart from the value.
func (q *Queries) GroupTotals(ctx context.Context, arg GroupTotalsParams) ([]GroupTotalsRow, error) {
	rows, err := q.db.Query(ctx, groupTotals, arg.GroupBy, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupTotalsRow
	for rows.Next() {
		var i GroupTotalsRow
		if err := rows.Scan(
			&i.Key,
			&i.EntryCount,
			&i.CardCount,
			&i.ValueEur,
			&i.UnpricedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setsByCode = `-- name: SetsByCode :many
SELECT code, name, icon_svg_uri, released_at FROM sets WHERE code = ANY ($1::text[])
`

type SetsByCodeRow struct {
	Code       string
	Name       string
	IconSvgUri pgtype.Text
	ReleasedAt pgtype.Date
}

// The sets with these codes: the groups when grouping by set.
func (q *Queries) SetsByCode(ctx context.Context, codes []string) ([]SetsByCodeRow, error) {
	rows, err := q.db.Query(ctx, setsByCode, codes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SetsByCodeRow
	for rows.Next() {
		var i SetsByCodeRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.IconSvgUri,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uniqueCards = `-- name: UniqueCards :one
SELECT count(DISTINCT card_id)::integer FROM collection_entries WHERE user_id = $1
`

// Distinct printings the user owns.
func (q *Queries) UniqueCards(ctx context.Context, userID int64) (int32, error) {
	row := q.db.QueryRow(ctx, uniqueCards, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE collection_entries
   SET quantity = $1, finish = $2, condition = $3, language = $4
 WHERE user_id = $5 AND id = $6
RETURNING id
`

type UpdateEntryParams struct {
	Quantity  int32
	Finish    string
	Condition string
	Language  string
	UserID    int64
	ID        int64
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.Quantity,
		arg.Finish,
		arg.Condition,
		arg.Language,
		arg.UserID,
		arg.ID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
