// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collection.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addEntry = `-- name: AddEntry :one
INSERT INTO collection_entries AS e (user_id, card_id, quantity, finish, condition, language)
SELECT $1, c.id, $2, $3, $4, $5
  FROM cards c
 WHERE c.id = $6 AND $3::text = ANY (c.finishes)
   AND ((SELECT count(*) FROM collection_entries WHERE user_id = $1) < $7::integer
        OR EXISTS (SELECT 1 FROM collection_entries
                    WHERE user_id = $1 AND card_id = $6 AND finish = $3
                      AND condition = $4 AND language = $5))
ON CONFLICT (user_id, card_id, finish, condition, language)
DO UPDATE SET quantity = e.quantity + excluded.quantity
        WHERE e.quantity + excluded.quantity <= $8::integer
RETURNING e.id, (xmax = 0)::boolean AS created
`

type AddEntryParams struct {
	UserID      int64
	Quantity    int32
	Finish      string
	Condition   string
	Language    string
	CardID      pgtype.UUID
	MaxEntries  int32
	MaxQuantity int32
}

type AddEntryRow struct {
	ID      int64
	Created bool
}

// Adds copies: a new entry, or more of one the user has with the same printing, finish,
// condition and language. No row when there's no such card, it doesn't come in that finish,
// there would be more than max_quantity copies, or it would be a new entry and the user already has
// max_entries. (That limit is approximate: adds at the same moment can each see room.)
func (q *Queries) AddEntry(ctx context.Context, arg AddEntryParams) (AddEntryRow, error) {
	row := q.db.QueryRow(ctx, addEntry,
		arg.UserID,
		arg.Quantity,
		arg.Finish,
		arg.Condition,
		arg.Language,
		arg.CardID,
		arg.MaxEntries,
		arg.MaxQuantity,
	)
	var i AddEntryRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}

const cardFinishes = `-- name: CardFinishes :one

SELECT finishes FROM cards WHERE id = $1
`

// Queries for the collection (internal/collection). Every query of entries is for one user's:
// user_id is in its WHERE clause. Prices come from the entry_prices view. Names sort by the
// "unicode" collation (ICU's root), so "Æther Vial" comes with the aethers, not after "Zur",
// whatever the database's own collation is.
func (q *Queries) CardFinishes(ctx context.Context, id pgtype.UUID) ([]string, error) {
	row := q.db.QueryRow(ctx, cardFinishes, id)
	var finishes []string
	err := row.Scan(&finishes)
	return finishes, err
}

const collectionStats = `-- name: CollectionStats :many
SELECT GROUPING(g.color, g.rarity)::integer AS totals_of,
       coalesce(g.color, '')::text AS color,
       coalesce(g.rarity, '')::text AS rarity,
       coalesce(sum(g.quantity), 0)::integer AS card_count,
       coalesce(sum(g.value), 0)::numeric AS value_eur,
       coalesce(sum(g.quantity) FILTER (WHERE g.unit_price IS NULL), 0)::integer AS unpriced_count,
       count(DISTINCT g.card_id)::integer AS unique_cards
  FROM (SELECT p.quantity, p.value, p.unit_price, p.card_id, p.rarity,
               card_group('color', p.set_code, p.color_identity, p.type_line, p.rarity, p.cmc) AS color
          FROM entry_prices p
         WHERE p.user_id = $1) g
 GROUP BY GROUPING SETS ((), (g.color), (g.rarity))
`

type CollectionStatsRow struct {
	TotalsOf      int32
	Color         string
	Rarity        string
	CardCount     int32
	ValueEur      pgtype.Numeric
	UnpricedCount int32
	UniqueCards   int32
}

// The user's totals in one pass: over everything (totals_of 3), by colour group (1) and by
// rarity (2). The whole-collection row is there even when the collection is empty.
func (q *Queries) CollectionStats(ctx context.Context, userID int64) ([]CollectionStatsRow, error) {
	rows, err := q.db.Query(ctx, collectionStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionStatsRow
	for rows.Next() {
		var i CollectionStatsRow
		if err := rows.Scan(
			&i.TotalsOf,
			&i.Color,
			&i.Rarity,
			&i.CardCount,
			&i.ValueEur,
			&i.UnpricedCount,
			&i.UniqueCards,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEntry = `-- name: DeleteEntry :execrows
DELETE FROM collection_entries WHERE user_id = $1 AND id = $2
`

type DeleteEntryParams struct {
	UserID int64
	ID     int64
}

func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEntry, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const entriesByAdded = `-- name: EntriesByAdded :many
SELECT p.group_id, p.id, p.user_id, p.card_id, p.quantity, p.finish, p.condition, p.language, p.added_at, p.name, p.set_code, p.color_identity, p.type_line, p.rarity, p.cmc, p.unit_price, p.value, p.count, p.count_value, p.listed_at, v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM listing_rows p
  JOIN card_listing v ON v.id = p.card_id
 WHERE p.group_id = $1 AND p.user_id = $2
   AND card_group($3, p.set_code, p.color_identity, p.type_line, p.rarity, p.cmc) = $4
   AND ($5::bigint IS NULL
        OR (p.listed_at, p.id) < ($6::timestamptz, $5::bigint))
 ORDER BY p.listed_at DESC, p.id DESC
 LIMIT $7
`

type EntriesByAddedParams struct {
	GroupID    int64
	UserID     int64
	GroupBy    string
	GroupKey   string
	AfterID    pgtype.Int8
	AfterAdded pgtype.Timestamptz
	RowLimit   int32
}

type EntriesByAddedRow struct {
	ListingRow  ListingRow
	CardListing CardListing
}

// Newest first: added to the collection, or to the group.
func (q *Queries) EntriesByAdded(ctx context.Context, arg EntriesByAddedParams) ([]EntriesByAddedRow, error) {
	rows, err := q.db.Query(ctx, entriesByAdded,
		arg.GroupID,
		arg.UserID,
		arg.GroupBy,
		arg.GroupKey,
		arg.AfterID,
		arg.AfterAdded,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntriesByAddedRow
	for rows.Next() {
		var i EntriesByAddedRow
		if err := rows.Scan(
			&i.ListingRow.GroupID,
			&i.ListingRow.ID,
			&i.ListingRow.UserID,
			&i.ListingRow.CardID,
			&i.ListingRow.Quantity,
			&i.ListingRow.Finish,
			&i.ListingRow.Condition,
			&i.ListingRow.Language,
			&i.ListingRow.AddedAt,
			&i.ListingRow.Name,
			&i.ListingRow.SetCode,
			&i.ListingRow.ColorIdentity,
			&i.ListingRow.TypeLine,
			&i.ListingRow.Rarity,
			&i.ListingRow.Cmc,
			&i.ListingRow.UnitPrice,
			&i.ListingRow.Value,
			&i.ListingRow.Count,
			&i.ListingRow.CountValue,
			&i.ListingRow.ListedAt,
			&i.CardListing.ID,
			&i.CardListing.OracleID,
			&i.CardListing.Name,
			&i.CardListing.Lang,
			&i.CardListing.SetCode,
			&i.CardListing.CollectorNumber,
			&i.CardListing.Rarity,
			&i.CardListing.Layout,
			&i.CardListing.ManaCost,
			&i.CardListing.Cmc,
			&i.CardListing.TypeLine,
			&i.CardListing.OracleText,
			&i.CardListing.Colors,
			&i.CardListing.ColorIdentity,
			&i.CardListing.Finishes,
			&i.CardListing.Images,
			&i.CardListing.Faces,
			&i.CardListing.PriceEur,
			&i.CardListing.PriceEurFoil,
			&i.CardListing.PriceUsd,
			&i.CardListing.PriceUsdFoil,
			&i.CardListing.PriceUsdEtched,
			&i.CardListing.CardmarketUrl,
			&i.CardListing.ReleasedAt,
			&i.CardListing.GoneSince,
			&i.CardListing.SetName,
			&i.CardListing.SetIconSvgUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesByCMC = `-- name: EntriesByCMC :many
SELECT p.group_id, p.id, p.user_id, p.card_id, p.quantity, p.finish, p.condition, p.language, p.added_at, p.name, p.set_code, p.color_identity, p.type_line, p.rarity, p.cmc, p.unit_price, p.value, p.count, p.count_value, p.listed_at, v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM listing_rows p
  JOIN card_listing v ON v.id = p.card_id
 WHERE p.group_id = $1 AND p.user_id = $2
   AND card_group($3, p.set_code, p.color_identity, p.type_line, p.rarity, p.cmc) = $4
   AND ($5::bigint IS NULL
        OR (p.cmc, p.name COLLATE "unicode", p.id)
         > ($6::numeric, $7::text COLLATE "unicode", $5::bigint))
 ORDER BY p.cmc, p.name COLLATE "unicode", p.id
 LIMIT $8
`

type EntriesByCMCParams struct {
	GroupID   int64
	UserID    int64
	GroupBy   string
	GroupKey  string
	AfterID   pgtype.Int8
	AfterCmc  pgtype.Numeric
	AfterName pgtype.Text
	RowLimit  int32
}

type EntriesByCMCRow struct {
	ListingRow  ListingRow
	CardListing CardListing
}

func (q *Queries) EntriesByCMC(ctx context.Context, arg EntriesByCMCParams) ([]EntriesByCMCRow, error) {
	rows, err := q.db.Query(ctx, entriesByCMC,
		arg.GroupID,
		arg.UserID,
		arg.GroupBy,
		arg.GroupKey,
		arg.AfterID,
		arg.AfterCmc,
		arg.AfterName,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntriesByCMCRow
	for rows.Next() {
		var i EntriesByCMCRow
		if err := rows.Scan(
			&i.ListingRow.GroupID,
			&i.ListingRow.ID,
			&i.ListingRow.UserID,
			&i.ListingRow.CardID,
			&i.ListingRow.Quantity,
			&i.ListingRow.Finish,
			&i.ListingRow.Condition,
			&i.ListingRow.Language,
			&i.ListingRow.AddedAt,
			&i.ListingRow.Name,
			&i.ListingRow.SetCode,
			&i.ListingRow.ColorIdentity,
			&i.ListingRow.TypeLine,
			&i.ListingRow.Rarity,
			&i.ListingRow.Cmc,
			&i.ListingRow.UnitPrice,
			&i.ListingRow.Value,
			&i.ListingRow.Count,
			&i.ListingRow.CountValue,
			&i.ListingRow.ListedAt,
			&i.CardListing.ID,
			&i.CardListing.OracleID,
			&i.CardListing.Name,
			&i.CardListing.Lang,
			&i.CardListing.SetCode,
			&i.CardListing.CollectorNumber,
			&i.CardListing.Rarity,
			&i.CardListing.Layout,
			&i.CardListing.ManaCost,
			&i.CardListing.Cmc,
			&i.CardListing.TypeLine,
			&i.CardListing.OracleText,
			&i.CardListing.Colors,
			&i.CardListing.ColorIdentity,
			&i.CardListing.Finishes,
			&i.CardListing.Images,
			&i.CardListing.Faces,
			&i.CardListing.PriceEur,
			&i.CardListing.PriceEurFoil,
			&i.CardListing.PriceUsd,
			&i.CardListing.PriceUsdFoil,
			&i.CardListing.PriceUsdEtched,
			&i.CardListing.CardmarketUrl,
			&i.CardListing.ReleasedAt,
			&i.CardListing.GoneSince,
			&i.CardListing.SetName,
			&i.CardListing.SetIconSvgUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesByName = `-- name: EntriesByName :many

SELECT p.group_id, p.id, p.user_id, p.card_id, p.quantity, p.finish, p.condition, p.language, p.added_at, p.name, p.set_code, p.color_identity, p.type_line, p.rarity, p.cmc, p.unit_price, p.value, p.count, p.count_value, p.listed_at, v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM listing_rows p
  JOIN card_listing v ON v.id = p.card_id
 WHERE p.group_id = $1 AND p.user_id = $2
   AND card_group($3, p.set_code, p.color_identity, p.type_line, p.rarity, p.cmc) = $4
   AND ($5::bigint IS NULL
        OR (p.name COLLATE "unicode", p.id) > ($6::text COLLATE "unicode", $5::bigint))
 ORDER BY p.name COLLATE "unicode", p.id
 LIMIT $7
`

type EntriesByNameParams struct {
	GroupID   int64
	UserID    int64
	GroupBy   string
	GroupKey  string
	AfterID   pgtype.Int8
	AfterName pgtype.Text
	RowLimit  int32
}

type EntriesByNameRow struct {
	ListingRow  ListingRow
	CardListing CardListing
}

// A page of the entries of the collection (group_id 0) or the members of a custom group, in
// one of the groups card_group makes of them (group_by 'none' is every one: key 'all'), in one
// order. Each order is its own query, so each can page by keyset: the page after the row
// whose sort key is the cursor's.
func (q *Queries) EntriesByName(ctx context.Context, arg EntriesByNameParams) ([]EntriesByNameRow, error) {
	rows, err := q.db.Query(ctx, entriesByName,
		arg.GroupID,
		arg.UserID,
		arg.GroupBy,
		arg.GroupKey,
		arg.AfterID,
		arg.AfterName,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntriesByNameRow
	for rows.Next() {
		var i EntriesByNameRow
		if err := rows.Scan(
			&i.ListingRow.GroupID,
			&i.ListingRow.ID,
			&i.ListingRow.UserID,
			&i.ListingRow.CardID,
			&i.ListingRow.Quantity,
			&i.ListingRow.Finish,
			&i.ListingRow.Condition,
			&i.ListingRow.Language,
			&i.ListingRow.AddedAt,
			&i.ListingRow.Name,
			&i.ListingRow.SetCode,
			&i.ListingRow.ColorIdentity,
			&i.ListingRow.TypeLine,
			&i.ListingRow.Rarity,
			&i.ListingRow.Cmc,
			&i.ListingRow.UnitPrice,
			&i.ListingRow.Value,
			&i.ListingRow.Count,
			&i.ListingRow.CountValue,
			&i.ListingRow.ListedAt,
			&i.CardListing.ID,
			&i.CardListing.OracleID,
			&i.CardListing.Name,
			&i.CardListing.Lang,
			&i.CardListing.SetCode,
			&i.CardListing.CollectorNumber,
			&i.CardListing.Rarity,
			&i.CardListing.Layout,
			&i.CardListing.ManaCost,
			&i.CardListing.Cmc,
			&i.CardListing.TypeLine,
			&i.CardListing.OracleText,
			&i.CardListing.Colors,
			&i.CardListing.ColorIdentity,
			&i.CardListing.Finishes,
			&i.CardListing.Images,
			&i.CardListing.Faces,
			&i.CardListing.PriceEur,
			&i.CardListing.PriceEurFoil,
			&i.CardListing.PriceUsd,
			&i.CardListing.PriceUsdFoil,
			&i.CardListing.PriceUsdEtched,
			&i.CardListing.CardmarketUrl,
			&i.CardListing.ReleasedAt,
			&i.CardListing.GoneSince,
			&i.CardListing.SetName,
			&i.CardListing.SetIconSvgUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entriesByPrice = `-- name: EntriesByPrice :many
SELECT p.group_id, p.id, p.user_id, p.card_id, p.quantity, p.finish, p.condition, p.language, p.added_at, p.name, p.set_code, p.color_identity, p.type_line, p.rarity, p.cmc, p.unit_price, p.value, p.count, p.count_value, p.listed_at, v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM listing_rows p
  JOIN card_listing v ON v.id = p.card_id
 WHERE p.group_id = $1 AND p.user_id = $2
   AND card_group($3, p.set_code, p.color_identity, p.type_line, p.rarity, p.cmc) = $4
   AND ($5::bigint IS NULL
        OR (p.unit_price IS NULL, -coalesce(p.unit_price, 0), p.id)
         > ($6::boolean, -coalesce($7::numeric, 0), $5::bigint))
 ORDER BY p.unit_price IS NULL, -coalesce(p.unit_price, 0), p.id
 LIMIT $8
`

type EntriesByPriceParams struct {
	GroupID       int64
	UserID        int64
	GroupBy       string
	GroupKey      string
	AfterID       pgtype.Int8
	AfterUnpriced pgtype.Bool
	AfterPrice    pgtype.Numeric
	RowLimit      int32
}

type EntriesByPriceRow struct {
	ListingRow  ListingRow
	CardListing CardListing
}

// Most valuable copy first; those with no price last.
func (q *Queries) EntriesByPrice(ctx context.Context, arg EntriesByPriceParams) ([]EntriesByPriceRow, error) {
	rows, err := q.db.Query(ctx, entriesByPrice,
		arg.GroupID,
		arg.UserID,
		arg.GroupBy,
		arg.GroupKey,
		arg.AfterID,
		arg.AfterUnpriced,
		arg.AfterPrice,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntriesByPriceRow
	for rows.Next() {
		var i EntriesByPriceRow
		if err := rows.Scan(
			&i.ListingRow.GroupID,
			&i.ListingRow.ID,
			&i.ListingRow.UserID,
			&i.ListingRow.CardID,
			&i.ListingRow.Quantity,
			&i.ListingRow.Finish,
			&i.ListingRow.Condition,
			&i.ListingRow.Language,
			&i.ListingRow.AddedAt,
			&i.ListingRow.Name,
			&i.ListingRow.SetCode,
			&i.ListingRow.ColorIdentity,
			&i.ListingRow.TypeLine,
			&i.ListingRow.Rarity,
			&i.ListingRow.Cmc,
			&i.ListingRow.UnitPrice,
			&i.ListingRow.Value,
			&i.ListingRow.Count,
			&i.ListingRow.CountValue,
			&i.ListingRow.ListedAt,
			&i.CardListing.ID,
			&i.CardListing.OracleID,
			&i.CardListing.Name,
			&i.CardListing.Lang,
			&i.CardListing.SetCode,
			&i.CardListing.CollectorNumber,
			&i.CardListing.Rarity,
			&i.CardListing.Layout,
			&i.CardListing.ManaCost,
			&i.CardListing.Cmc,
			&i.CardListing.TypeLine,
			&i.CardListing.OracleText,
			&i.CardListing.Colors,
			&i.CardListing.ColorIdentity,
			&i.CardListing.Finishes,
			&i.CardListing.Images,
			&i.CardListing.Faces,
			&i.CardListing.PriceEur,
			&i.CardListing.PriceEurFoil,
			&i.CardListing.PriceUsd,
			&i.CardListing.PriceUsdFoil,
			&i.CardListing.PriceUsdEtched,
			&i.CardListing.CardmarketUrl,
			&i.CardListing.ReleasedAt,
			&i.CardListing.GoneSince,
			&i.CardListing.SetName,
			&i.CardListing.SetIconSvgUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entryCard = `-- name: EntryCard :one
SELECT e.quantity, e.finish, e.condition, e.language, c.finishes
  FROM collection_entries e
  JOIN cards c ON c.id = e.card_id
 WHERE e.user_id = $1 AND e.id = $2
`

type EntryCardParams struct {
	UserID int64
	ID     int64
}

type EntryCardRow struct {
	Quantity  int32
	Finish    string
	Condition string
	Language  string
	Finishes  []string
}

// What an entry is, for checking a change to it.
func (q *Queries) EntryCard(ctx context.Context, arg EntryCardParams) (EntryCardRow, error) {
	row := q.db.QueryRow(ctx, entryCard, arg.UserID, arg.ID)
	var i EntryCardRow
	err := row.Scan(
		&i.Quantity,
		&i.Finish,
		&i.Condition,
		&i.Language,
		&i.Finishes,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT p.group_id, p.id, p.user_id, p.card_id, p.quantity, p.finish, p.condition, p.language, p.added_at, p.name, p.set_code, p.color_identity, p.type_line, p.rarity, p.cmc, p.unit_price, p.value, p.count, p.count_value, p.listed_at, v.id, v.oracle_id, v.name, v.lang, v.set_code, v.collector_number, v.rarity, v.layout, v.mana_cost, v.cmc, v.type_line, v.oracle_text, v.colors, v.color_identity, v.finishes, v.images, v.faces, v.price_eur, v.price_eur_foil, v.price_usd, v.price_usd_foil, v.price_usd_etched, v.cardmarket_url, v.released_at, v.gone_since, v.set_name, v.set_icon_svg_uri
  FROM listing_rows p
  JOIN card_listing v ON v.id = p.card_id
 WHERE p.group_id = $1 AND p.user_id = $2 AND p.id = $3
`

type GetEntryParams struct {
	GroupID int64
	UserID  int64
	ID      int64
}

type GetEntryRow struct {
	ListingRow  ListingRow
	CardListing CardListing
}

// One entry of the collection (group 0), or one member of a group.
func (q *Queries) GetEntry(ctx context.Context, arg GetEntryParams) (GetEntryRow, error) {
	row := q.db.QueryRow(ctx, getEntry, arg.GroupID, arg.UserID, arg.ID)
	var i GetEntryRow
	err := row.Scan(
		&i.ListingRow.GroupID,
		&i.ListingRow.ID,
		&i.ListingRow.UserID,
		&i.ListingRow.CardID,
		&i.ListingRow.Quantity,
		&i.ListingRow.Finish,
		&i.ListingRow.Condition,
		&i.ListingRow.Language,
		&i.ListingRow.AddedAt,
		&i.ListingRow.Name,
		&i.ListingRow.SetCode,
		&i.ListingRow.ColorIdentity,
		&i.ListingRow.TypeLine,
		&i.ListingRow.Rarity,
		&i.ListingRow.Cmc,
		&i.ListingRow.UnitPrice,
		&i.ListingRow.Value,
		&i.ListingRow.Count,
		&i.ListingRow.CountValue,
		&i.ListingRow.ListedAt,
		&i.CardListing.ID,
		&i.CardListing.OracleID,
		&i.CardListing.Name,
		&i.CardListing.Lang,
		&i.CardListing.SetCode,
		&i.CardListing.CollectorNumber,
		&i.CardListing.Rarity,
		&i.CardListing.Layout,
		&i.CardListing.ManaCost,
		&i.CardListing.Cmc,
		&i.CardListing.TypeLine,
		&i.CardListing.OracleText,
		&i.CardListing.Colors,
		&i.CardListing.ColorIdentity,
		&i.CardListing.Finishes,
		&i.CardListing.Images,
		&i.CardListing.Faces,
		&i.CardListing.PriceEur,
		&i.CardListing.PriceEurFoil,
		&i.CardListing.PriceUsd,
		&i.CardListing.PriceUsdFoil,
		&i.CardListing.PriceUsdEtched,
		&i.CardListing.CardmarketUrl,
		&i.CardListing.ReleasedAt,
		&i.CardListing.GoneSince,
		&i.CardListing.SetName,
		&i.CardListing.SetIconSvgUri,
	)
	return i, err
}

const groupTotals = `-- name: GroupTotals :many
SELECT card_group($1, p.set_code, p.color_identity, p.type_line, p.rarity, p.cmc)::text AS key,
       count(*)::integer AS entry_count,
       sum(p.count)::integer AS card_count,
       coalesce(sum(p.count_value), 0)::numeric AS value_eur,
       coalesce(sum(p.count) FILTER (WHERE p.unit_price IS NULL), 0)::integer AS unpriced_count
  FROM listing_rows p
 WHERE p.group_id = $2 AND p.user_id = $3
 GROUP BY 1
`

type GroupTotalsParams struct {
	GroupBy string
	GroupID int64
	UserID  int64
}

type GroupTotalsRow struct {
	Key           string
	EntryCount    int32
	CardCount     int32
	ValueEur      pgtype.Numeric
	UnpricedCount int32
}

// The groups of the user's collection (group 0) or one of their custom groups, for one way of
// grouping, with their totals: of the copies listed (a member's, in a custom group). Cards
// with no price are counted apart from the value.
func (q *Queries) GroupTotals(ctx context.Context, arg GroupTotalsParams) ([]GroupTotalsRow, error) {
	rows, err := q.db.Query(ctx, groupTotals, arg.GroupBy, arg.GroupID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupTotalsRow
	for rows.Next() {
		var i GroupTotalsRow
		if err := rows.Scan(
			&i.Key,
			&i.EntryCount,
			&i.CardCount,
			&i.ValueEur,
			&i.UnpricedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasEntry = `-- name: HasEntry :one

SELECT EXISTS (SELECT 1 FROM collection_entries
                WHERE user_id = $1 AND card_id = $2 AND finish = $3
                  AND condition = $4 AND language = $5)
`

type HasEntryParams struct {
	UserID    int64
	CardID    pgtype.UUID
	Finish    string
	Condition string
	Language  string
}

// xmax is 0 for a row this statement inserted
// Whether the user has an entry for this printing, finish, condition and language.
func (q *Queries) HasEntry(ctx context.Context, arg HasEntryParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasEntry,
		arg.UserID,
		arg.CardID,
		arg.Finish,
		arg.Condition,
		arg.Language,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setsByCode = `-- name: SetsByCode :many
SELECT code, name, icon_svg_uri, released_at FROM sets WHERE code = ANY ($1::text[])
`

type SetsByCodeRow struct {
	Code       string
	Name       string
	IconSvgUri pgtype.Text
	ReleasedAt pgtype.Date
}

// The sets with these codes: the groups when grouping by set.
func (q *Queries) SetsByCode(ctx context.Context, codes []string) ([]SetsByCodeRow, error) {
	rows, err := q.db.Query(ctx, setsByCode, codes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SetsByCodeRow
	for rows.Next() {
		var i SetsByCodeRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.IconSvgUri,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE collection_entries
   SET quantity = $1, finish = $2, condition = $3, language = $4
 WHERE user_id = $5 AND id = $6
RETURNING id
`

type UpdateEntryParams struct {
	Quantity  int32
	Finish    string
	Condition string
	Language  string
	UserID    int64
	ID        int64
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.Quantity,
		arg.Finish,
		arg.Condition,
		arg.Language,
		arg.UserID,
		arg.ID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
