// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForStageCards implements pgx.CopyFromSource.
type iteratorForStageCards struct {
	rows                 []StageCardsParams
	skippedFirstNextCall bool
}

func (r *iteratorForStageCards) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForStageCards) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].OracleID,
		r.rows[0].Name,
		r.rows[0].Lang,
		r.rows[0].SetCode,
		r.rows[0].CollectorNumber,
		r.rows[0].Rarity,
		r.rows[0].Layout,
		r.rows[0].ManaCost,
		r.rows[0].Cmc,
		r.rows[0].TypeLine,
		r.rows[0].OracleText,
		r.rows[0].Colors,
		r.rows[0].ColorIdentity,
		r.rows[0].Finishes,
		r.rows[0].Images,
		r.rows[0].Faces,
		r.rows[0].PriceEur,
		r.rows[0].PriceEurFoil,
		r.rows[0].PriceUsd,
		r.rows[0].PriceUsdFoil,
		r.rows[0].PriceUsdEtched,
		r.rows[0].CardmarketID,
		r.rows[0].CardmarketUrl,
		r.rows[0].ReleasedAt,
	}, nil
}

func (r iteratorForStageCards) Err() error {
	return nil
}

func (q *Queries) StageCards(ctx context.Context, arg []StageCardsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"cards_staging"}, []string{"id", "oracle_id", "name", "lang", "set_code", "collector_number", "rarity", "layout", "mana_cost", "cmc", "type_line", "oracle_text", "colors", "color_identity", "finishes", "images", "faces", "price_eur", "price_eur_foil", "price_usd", "price_usd_foil", "price_usd_etched", "cardmarket_id", "cardmarket_url", "released_at"}, &iteratorForStageCards{rows: arg})
}
