// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToGroup = `-- name: AddToGroup :exec
INSERT INTO group_members AS m (group_id, entry_id, user_id, quantity)
SELECT g.id, e.id, g.user_id, least($1::integer, e.quantity)
  FROM custom_groups g, collection_entries e
 WHERE g.id = $2 AND g.user_id = $3 AND e.id = $4 AND e.user_id = $3
ON CONFLICT (group_id, entry_id) DO UPDATE SET quantity = least(m.quantity + excluded.quantity,
    (SELECT quantity FROM collection_entries WHERE id = excluded.entry_id))
`

type AddToGroupParams struct {
	Quantity int32
	GroupID  int64
	UserID   int64
	EntryID  int64
}

// Puts copies just added to an entry in a group too (or more of them, if they're there): never
// more than the entry has.
func (q *Queries) AddToGroup(ctx context.Context, arg AddToGroupParams) error {
	_, err := q.db.Exec(ctx, addToGroup,
		arg.Quantity,
		arg.GroupID,
		arg.UserID,
		arg.EntryID,
	)
	return err
}

const createGroup = `-- name: CreateGroup :one

INSERT INTO custom_groups (user_id, name, kind, description)
SELECT $1, $2, $3, $4
 WHERE (SELECT count(*) FROM custom_groups WHERE user_id = $1) < $5::integer
RETURNING id
`

type CreateGroupParams struct {
	UserID      int64
	Name        string
	Kind        string
	Description string
	MaxGroups   int32
}

// Queries for custom groups (internal/collection customgroups.go): binders, decks and boxes,
// and their members. Every one is for one user's: user_id is in its WHERE clause.
// No row when the user already has max_groups groups. (Approximate: creations at the same
// moment can each see room.) A name the user already has is a unique violation.
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (int64, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.UserID,
		arg.Name,
		arg.Kind,
		arg.Description,
		arg.MaxGroups,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM custom_groups WHERE user_id = $1 AND id = $2
`

type DeleteGroupParams struct {
	UserID int64
	ID     int64
}

// Its members go with it; the entries stay in the collection.
func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroup, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const entryQuantity = `-- name: EntryQuantity :one
SELECT quantity FROM collection_entries WHERE user_id = $1 AND id = $2
`

type EntryQuantityParams struct {
	UserID int64
	ID     int64
}

// How many copies one of the user's entries has.
func (q *Queries) EntryQuantity(ctx context.Context, arg EntryQuantityParams) (int32, error) {
	row := q.db.QueryRow(ctx, entryQuantity, arg.UserID, arg.ID)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const groupExists = `-- name: GroupExists :one
SELECT EXISTS (SELECT 1 FROM custom_groups WHERE user_id = $1 AND id = $2)
`

type GroupExistsParams struct {
	UserID int64
	ID     int64
}

func (q *Queries) GroupExists(ctx context.Context, arg GroupExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, groupExists, arg.UserID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const groupPreviews = `-- name: GroupPreviews :many
SELECT x.group_id, x.images
  FROM (SELECT d.group_id, d.images,
               row_number() OVER (PARTITION BY d.group_id
                                  ORDER BY d.unit_price DESC NULLS LAST, d.added_at, d.card_id) AS n
          FROM (SELECT DISTINCT ON (m.group_id, p.card_id) m.group_id, p.card_id, c.images, p.unit_price, m.added_at
                  FROM group_members m
                  JOIN entry_prices p ON p.id = m.entry_id
                  JOIN cards c ON c.id = p.card_id
                 WHERE m.user_id = $1
                   AND ($2::bigint IS NULL OR m.group_id = $2::bigint)
                   AND c.images IS NOT NULL
                 ORDER BY m.group_id, p.card_id, p.unit_price DESC NULLS LAST, m.added_at) d) x
 WHERE x.n <= 4
 ORDER BY x.group_id, x.n
`

type GroupPreviewsParams struct {
	UserID  int64
	GroupID pgtype.Int8
}

type GroupPreviewsRow struct {
	GroupID int64
	Images  []byte
}

// Up to four card images for each of the user's groups (or the one with group_id): its most
// valuable cards', each card once.
func (q *Queries) GroupPreviews(ctx context.Context, arg GroupPreviewsParams) ([]GroupPreviewsRow, error) {
	rows, err := q.db.Query(ctx, groupPreviews, arg.UserID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupPreviewsRow
	for rows.Next() {
		var i GroupPreviewsRow
		if err := rows.Scan(&i.GroupID, &i.Images); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT g.id, g.name, g.kind, g.description,
       coalesce(sum(m.quantity), 0)::integer AS card_count,
       coalesce(sum(line_value(p.unit_price, m.quantity)), 0)::numeric AS value_eur,
       coalesce(sum(m.quantity) FILTER (WHERE m.entry_id IS NOT NULL AND p.unit_price IS NULL), 0)::integer AS unpriced_count
  FROM custom_groups g
  LEFT JOIN group_members m ON m.group_id = g.id
  LEFT JOIN entry_prices p ON p.id = m.entry_id
 WHERE g.user_id = $1
   AND ($2::bigint IS NULL OR g.id = $2::bigint)
 GROUP BY g.id
 ORDER BY g.name COLLATE "unicode", g.id
`

type ListGroupsParams struct {
	UserID  int64
	GroupID pgtype.Int8
}

type ListGroupsRow struct {
	ID            int64
	Name          string
	Kind          string
	Description   string
	CardCount     int32
	ValueEur      pgtype.Numeric
	UnpricedCount int32
}

// The user's groups (or the one with group_id), by name, with their totals: of the copies in
// each, priced as the collection's are.
func (q *Queries) ListGroups(ctx context.Context, arg ListGroupsParams) ([]ListGroupsRow, error) {
	rows, err := q.db.Query(ctx, listGroups, arg.UserID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsRow
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Description,
			&i.CardCount,
			&i.ValueEur,
			&i.UnpricedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :execrows
DELETE FROM group_members WHERE user_id = $1 AND group_id = $2 AND entry_id = $3
`

type RemoveMemberParams struct {
	UserID  int64
	GroupID int64
	EntryID int64
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMember, arg.UserID, arg.GroupID, arg.EntryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMember = `-- name: SetMember :one
WITH entry AS (
    SELECT e.id, e.quantity
      FROM collection_entries e
     WHERE e.id = $4 AND e.user_id = $3
       FOR SHARE
)
INSERT INTO group_members AS m (group_id, entry_id, user_id, quantity)
SELECT g.id, entry.id, g.user_id, $1
  FROM entry, custom_groups g
 WHERE g.id = $2 AND g.user_id = $3 AND entry.quantity >= $1::integer
ON CONFLICT (group_id, entry_id) DO UPDATE SET quantity = excluded.quantity
RETURNING (xmax = 0)::boolean AS created
`

type SetMemberParams struct {
	Quantity int32
	GroupID  int64
	UserID   int64
	EntryID  int64
}

// Puts quantity copies of one of the user's entries in one of their groups (or sets how many
// are there). Reads the entry FOR SHARE first, so a change to its quantity can't slip in
// between. No row when there's no such group or entry, or the entry has fewer copies.
func (q *Queries) SetMember(ctx context.Context, arg SetMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, setMember,
		arg.Quantity,
		arg.GroupID,
		arg.UserID,
		arg.EntryID,
	)
	var created bool
	err := row.Scan(&created)
	return created, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE custom_groups SET name = $1, kind = $2, description = $3
 WHERE user_id = $4 AND id = $5
RETURNING id
`

type UpdateGroupParams struct {
	Name        string
	Kind        string
	Description string
	UserID      int64
	ID          int64
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.Name,
		arg.Kind,
		arg.Description,
		arg.UserID,
		arg.ID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
