// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID              pgtype.UUID
	OracleID        pgtype.UUID
	Name            string
	Lang            string
	SetCode         string
	CollectorNumber string
	Rarity          string
	Layout          string
	ManaCost        string
	Cmc             pgtype.Numeric
	TypeLine        string
	OracleText      pgtype.Text
	Colors          []string
	ColorIdentity   []string
	Finishes        []string
	Images          []byte
	Faces           []byte
	PriceEur        pgtype.Numeric
	PriceEurFoil    pgtype.Numeric
	PriceUsd        pgtype.Numeric
	PriceUsdFoil    pgtype.Numeric
	PriceUsdEtched  pgtype.Numeric
	CardmarketID    pgtype.Int4
	CardmarketUrl   pgtype.Text
	ReleasedAt      pgtype.Date
	GoneSince       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type CardListing struct {
	ID              pgtype.UUID
	OracleID        pgtype.UUID
	Name            string
	Lang            string
	SetCode         string
	CollectorNumber string
	Rarity          string
	Layout          string
	ManaCost        string
	Cmc             pgtype.Numeric
	TypeLine        string
	OracleText      pgtype.Text
	Colors          []string
	ColorIdentity   []string
	Finishes        []string
	Images          []byte
	Faces           []byte
	PriceEur        pgtype.Numeric
	PriceEurFoil    pgtype.Numeric
	PriceUsd        pgtype.Numeric
	PriceUsdFoil    pgtype.Numeric
	PriceUsdEtched  pgtype.Numeric
	CardmarketUrl   pgtype.Text
	ReleasedAt      pgtype.Date
	GoneSince       pgtype.Timestamptz
	SetName         string
	SetIconSvgUri   pgtype.Text
}

type CardsStaging struct {
	ID              pgtype.UUID
	OracleID        pgtype.UUID
	Name            string
	Lang            string
	SetCode         string
	CollectorNumber string
	Rarity          string
	Layout          string
	ManaCost        string
	Cmc             pgtype.Numeric
	TypeLine        string
	OracleText      pgtype.Text
	Colors          []string
	ColorIdentity   []string
	Finishes        []string
	Images          []byte
	Faces           []byte
	PriceEur        pgtype.Numeric
	PriceEurFoil    pgtype.Numeric
	PriceUsd        pgtype.Numeric
	PriceUsdFoil    pgtype.Numeric
	PriceUsdEtched  pgtype.Numeric
	CardmarketID    pgtype.Int4
	CardmarketUrl   pgtype.Text
	ReleasedAt      pgtype.Date
	GoneSince       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type CollectionEntry struct {
	ID        int64
	UserID    int64
	CardID    pgtype.UUID
	Quantity  int32
	Finish    string
	Condition string
	Language  string
	AddedAt   pgtype.Timestamptz
}

type CustomGroup struct {
	ID          int64
	UserID      int64
	Name        string
	Kind        string
	Description string
	CreatedAt   pgtype.Timestamptz
}

type EntryPrice struct {
	ID            int64
	UserID        int64
	CardID        pgtype.UUID
	Quantity      int32
	Finish        string
	Condition     string
	Language      string
	AddedAt       pgtype.Timestamptz
	Name          string
	SetCode       string
	ColorIdentity []string
	TypeLine      string
	Rarity        string
	Cmc           pgtype.Numeric
	UnitPrice     pgtype.Numeric
	Value         pgtype.Numeric
}

type GroupMember struct {
	GroupID  int64
	EntryID  int64
	UserID   int64
	Quantity int32
	AddedAt  pgtype.Timestamptz
}

type ListingRow struct {
	GroupID       int64
	ID            int64
	UserID        int64
	CardID        pgtype.UUID
	Quantity      int32
	Finish        string
	Condition     string
	Language      string
	AddedAt       pgtype.Timestamptz
	Name          string
	SetCode       string
	ColorIdentity []string
	TypeLine      string
	Rarity        string
	Cmc           pgtype.Numeric
	UnitPrice     pgtype.Numeric
	Value         pgtype.Numeric
	Count         int32
	CountValue    pgtype.Numeric
	ListedAt      pgtype.Timestamptz
}

type ScryfallSync struct {
	ID            int64
	StartedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	BulkUpdatedAt pgtype.Timestamptz
	SetsSeen      pgtype.Int4
	CardsSeen     pgtype.Int4
	CardsSkipped  pgtype.Int4
	CardsChanged  pgtype.Int4
	CardsGone     pgtype.Int4
	Error         pgtype.Text
}

type Session struct {
	TokenHash []byte
	UserID    int64
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type Set struct {
	Code          string
	ScryfallID    pgtype.UUID
	Name          string
	SetType       string
	ReleasedAt    pgtype.Date
	IconSvgUri    pgtype.Text
	ParentSetCode pgtype.Text
	UpdatedAt     pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
