// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID              pgtype.UUID
	OracleID        pgtype.UUID
	Name            string
	Lang            string
	SetCode         string
	CollectorNumber string
	Rarity          string
	Layout          string
	ManaCost        string
	Cmc             pgtype.Numeric
	TypeLine        string
	OracleText      pgtype.Text
	Colors          []string
	ColorIdentity   []string
	Finishes        []string
	Images          []byte
	Faces           []byte
	PriceEur        pgtype.Numeric
	PriceEurFoil    pgtype.Numeric
	PriceUsd        pgtype.Numeric
	PriceUsdFoil    pgtype.Numeric
	PriceUsdEtched  pgtype.Numeric
	CardmarketID    pgtype.Int4
	CardmarketUrl   pgtype.Text
	ReleasedAt      pgtype.Date
	GoneSince       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type CardListing struct {
	ID              pgtype.UUID
	OracleID        pgtype.UUID
	Name            string
	Lang            string
	SetCode         string
	CollectorNumber string
	Rarity          string
	Layout          string
	ManaCost        string
	Cmc             pgtype.Numeric
	TypeLine        string
	OracleText      pgtype.Text
	Colors          []string
	ColorIdentity   []string
	Finishes        []string
	Images          []byte
	Faces           []byte
	PriceEur        pgtype.Numeric
	PriceEurFoil    pgtype.Numeric
	PriceUsd        pgtype.Numeric
	PriceUsdFoil    pgtype.Numeric
	PriceUsdEtched  pgtype.Numeric
	CardmarketUrl   pgtype.Text
	ReleasedAt      pgtype.Date
	GoneSince       pgtype.Timestamptz
	SetName         string
	SetIconSvgUri   pgtype.Text
}

type CardsStaging struct {
	ID              pgtype.UUID
	OracleID        pgtype.UUID
	Name            string
	Lang            string
	SetCode         string
	CollectorNumber string
	Rarity          string
	Layout          string
	ManaCost        string
	Cmc             pgtype.Numeric
	TypeLine        string
	OracleText      pgtype.Text
	Colors          []string
	ColorIdentity   []string
	Finishes        []string
	Images          []byte
	Faces           []byte
	PriceEur        pgtype.Numeric
	PriceEurFoil    pgtype.Numeric
	PriceUsd        pgtype.Numeric
	PriceUsdFoil    pgtype.Numeric
	PriceUsdEtched  pgtype.Numeric
	CardmarketID    pgtype.Int4
	CardmarketUrl   pgtype.Text
	ReleasedAt      pgtype.Date
	GoneSince       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ScryfallSync struct {
	ID            int64
	StartedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	BulkUpdatedAt pgtype.Timestamptz
	SetsSeen      pgtype.Int4
	CardsSeen     pgtype.Int4
	CardsSkipped  pgtype.Int4
	CardsChanged  pgtype.Int4
	CardsGone     pgtype.Int4
	Error         pgtype.Text
}

type Set struct {
	Code          string
	ScryfallID    pgtype.UUID
	Name          string
	SetType       string
	ReleasedAt    pgtype.Date
	IconSvgUri    pgtype.Text
	ParentSetCode pgtype.Text
	UpdatedAt     pgtype.Timestamptz
}
