// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scryfall.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const analyzeStagedCards = `-- name: AnalyzeStagedCards :exec
ANALYZE cards_staging
`

// Gives the planner the staged table's real size before the merge (autovacuum won't have yet).
func (q *Queries) AnalyzeStagedCards(ctx context.Context) error {
	_, err := q.db.Exec(ctx, analyzeStagedCards)
	return err
}

const clearStagedCards = `-- name: ClearStagedCards :exec
TRUNCATE cards_staging
`

func (q *Queries) ClearStagedCards(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearStagedCards)
	return err
}

const countCards = `-- name: CountCards :one
SELECT count(*) AS present,
       count(*) FILTER (WHERE NOT EXISTS (SELECT FROM cards_staging s WHERE s.id = c.id)) AS unstaged
  FROM cards c
 WHERE c.gone_since IS NULL
`

type CountCardsRow struct {
	Present  int64
	Unstaged int64
}

// Cards in the latest bulk file (not gone), and how many of those aren't staged now: the
// ones this import would mark gone.
func (q *Queries) CountCards(ctx context.Context) (CountCardsRow, error) {
	row := q.db.QueryRow(ctx, countCards)
	var i CountCardsRow
	err := row.Scan(&i.Present, &i.Unstaged)
	return i, err
}

const failedImportsOf = `-- name: FailedImportsOf :one
SELECT count(*)
  FROM scryfall_syncs
 WHERE bulk_updated_at = $1 AND (error IS NOT NULL OR finished_at IS NULL)
`

// How many imports of this bulk file have failed (or never finished).
func (q *Queries) FailedImportsOf(ctx context.Context, bulkUpdatedAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, failedImportsOf, bulkUpdatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishSync = `-- name: FinishSync :exec
UPDATE scryfall_syncs
   SET finished_at   = now(),
       sets_seen     = $2,
       cards_seen    = $3,
       cards_skipped = $4,
       cards_changed = $5,
       cards_gone    = $6,
       error         = $7
 WHERE id = $1
`

type FinishSyncParams struct {
	ID           int64
	SetsSeen     pgtype.Int4
	CardsSeen    pgtype.Int4
	CardsSkipped pgtype.Int4
	CardsChanged pgtype.Int4
	CardsGone    pgtype.Int4
	Error        pgtype.Text
}

func (q *Queries) FinishSync(ctx context.Context, arg FinishSyncParams) error {
	_, err := q.db.Exec(ctx, finishSync,
		arg.ID,
		arg.SetsSeen,
		arg.CardsSeen,
		arg.CardsSkipped,
		arg.CardsChanged,
		arg.CardsGone,
		arg.Error,
	)
	return err
}

const lastImport = `-- name: LastImport :one
SELECT id, started_at, finished_at, bulk_updated_at, sets_seen, cards_seen, cards_skipped, cards_changed, cards_gone, error
  FROM scryfall_syncs
 WHERE finished_at IS NOT NULL AND error IS NULL
 ORDER BY finished_at DESC
 LIMIT 1
`

// The most recent import that read a bulk file and succeeded.
func (q *Queries) LastImport(ctx context.Context) (ScryfallSync, error) {
	row := q.db.QueryRow(ctx, lastImport)
	var i ScryfallSync
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.BulkUpdatedAt,
		&i.SetsSeen,
		&i.CardsSeen,
		&i.CardsSkipped,
		&i.CardsChanged,
		&i.CardsGone,
		&i.Error,
	)
	return i, err
}

const markGoneCards = `-- name: MarkGoneCards :execrows
UPDATE cards c
   SET gone_since = now(), price_eur = NULL, price_eur_foil = NULL, price_usd = NULL,
       price_usd_foil = NULL, price_usd_etched = NULL, updated_at = now()
 WHERE c.gone_since IS NULL
   AND NOT EXISTS (SELECT FROM cards_staging s WHERE s.id = c.id)
`

// Cards that weren't in this import: Scryfall deleted or merged them, made them digital-only,
// or they couldn't be read. Their prices are cleared so no total keeps using a frozen price;
// the rows stay, as collections may refer to them.
func (q *Queries) MarkGoneCards(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markGoneCards)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const mergeStagedCards = `-- name: MergeStagedCards :execrows
INSERT INTO cards (
    id, oracle_id, name, lang, set_code, collector_number, rarity, layout, mana_cost, cmc,
    type_line, oracle_text, colors, color_identity, finishes, images, faces,
    price_eur, price_eur_foil, price_usd, price_usd_foil, price_usd_etched,
    cardmarket_id, cardmarket_url, released_at
)
SELECT DISTINCT ON (s.id)
    s.id, s.oracle_id, s.name, s.lang, s.set_code, s.collector_number, s.rarity, s.layout, s.mana_cost, s.cmc,
    s.type_line, s.oracle_text, s.colors, s.color_identity, s.finishes, s.images, s.faces,
    s.price_eur, s.price_eur_foil, s.price_usd, s.price_usd_foil, s.price_usd_etched,
    s.cardmarket_id, s.cardmarket_url, s.released_at
  FROM cards_staging s
  LEFT JOIN cards c ON c.id = s.id
 WHERE c.id IS NULL
    OR c.gone_since IS NOT NULL
    OR (c.oracle_id, c.name, c.lang, c.set_code, c.collector_number, c.rarity, c.layout, c.mana_cost,
        c.cmc, c.type_line, c.oracle_text, c.colors, c.color_identity, c.finishes, c.images, c.faces,
        c.price_eur, c.price_eur_foil, c.price_usd, c.price_usd_foil, c.price_usd_etched,
        c.cardmarket_id, c.cardmarket_url, c.released_at)
       IS DISTINCT FROM
       (s.oracle_id, s.name, s.lang, s.set_code, s.collector_number, s.rarity, s.layout, s.mana_cost,
        s.cmc, s.type_line, s.oracle_text, s.colors, s.color_identity, s.finishes, s.images, s.faces,
        s.price_eur, s.price_eur_foil, s.price_usd, s.price_usd_foil, s.price_usd_etched,
        s.cardmarket_id, s.cardmarket_url, s.released_at)
 ORDER BY s.id
ON CONFLICT (id) DO UPDATE
   SET oracle_id        = EXCLUDED.oracle_id,
       name             = EXCLUDED.name,
       lang             = EXCLUDED.lang,
       set_code         = EXCLUDED.set_code,
       collector_number = EXCLUDED.collector_number,
       rarity           = EXCLUDED.rarity,
       layout           = EXCLUDED.layout,
       mana_cost        = EXCLUDED.mana_cost,
       cmc              = EXCLUDED.cmc,
       type_line        = EXCLUDED.type_line,
       oracle_text      = EXCLUDED.oracle_text,
       colors           = EXCLUDED.colors,
       color_identity   = EXCLUDED.color_identity,
       finishes         = EXCLUDED.finishes,
       images           = EXCLUDED.images,
       faces            = EXCLUDED.faces,
       price_eur        = EXCLUDED.price_eur,
       price_eur_foil   = EXCLUDED.price_eur_foil,
       price_usd        = EXCLUDED.price_usd,
       price_usd_foil   = EXCLUDED.price_usd_foil,
       price_usd_etched = EXCLUDED.price_usd_etched,
       cardmarket_id    = EXCLUDED.cardmarket_id,
       cardmarket_url   = EXCLUDED.cardmarket_url,
       released_at      = EXCLUDED.released_at,
       gone_since       = NULL,
       updated_at       = now()
`

// Moves the staged cards into cards. Only new cards, changed cards and cards coming back
// after being gone are written: the rest aren't touched, so a daily import that moves a
// few prices rewrites (and locks, and logs) just those rows. Returns how many were written.
func (q *Queries) MergeStagedCards(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, mergeStagedCards)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

type StageCardsParams struct {
	ID              pgtype.UUID
	OracleID        pgtype.UUID
	Name            string
	Lang            string
	SetCode         string
	CollectorNumber string
	Rarity          string
	Layout          string
	ManaCost        string
	Cmc             pgtype.Numeric
	TypeLine        string
	OracleText      pgtype.Text
	Colors          []string
	ColorIdentity   []string
	Finishes        []string
	Images          []byte
	Faces           []byte
	PriceEur        pgtype.Numeric
	PriceEurFoil    pgtype.Numeric
	PriceUsd        pgtype.Numeric
	PriceUsdFoil    pgtype.Numeric
	PriceUsdEtched  pgtype.Numeric
	CardmarketID    pgtype.Int4
	CardmarketUrl   pgtype.Text
	ReleasedAt      pgtype.Date
}

const startSync = `-- name: StartSync :one
INSERT INTO scryfall_syncs (bulk_updated_at)
VALUES ($1)
RETURNING id
`

func (q *Queries) StartSync(ctx context.Context, bulkUpdatedAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, startSync, bulkUpdatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}
