// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scryfall.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearStagedCards = `-- name: ClearStagedCards :exec
TRUNCATE cards_staging
`

func (q *Queries) ClearStagedCards(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearStagedCards)
	return err
}

const finishSync = `-- name: FinishSync :exec
UPDATE scryfall_syncs
   SET finished_at     = now(),
       bulk_updated_at = $2,
       sets_seen       = $3,
       cards_seen      = $4,
       cards_skipped   = $5,
       cards_changed   = $6,
       error           = $7
 WHERE id = $1
`

type FinishSyncParams struct {
	ID            int64
	BulkUpdatedAt pgtype.Timestamptz
	SetsSeen      pgtype.Int4
	CardsSeen     pgtype.Int4
	CardsSkipped  pgtype.Int4
	CardsChanged  pgtype.Int4
	Error         pgtype.Text
}

func (q *Queries) FinishSync(ctx context.Context, arg FinishSyncParams) error {
	_, err := q.db.Exec(ctx, finishSync,
		arg.ID,
		arg.BulkUpdatedAt,
		arg.SetsSeen,
		arg.CardsSeen,
		arg.CardsSkipped,
		arg.CardsChanged,
		arg.Error,
	)
	return err
}

const lastSuccessfulSync = `-- name: LastSuccessfulSync :one
SELECT id, started_at, finished_at, bulk_updated_at, sets_seen, cards_seen, cards_skipped, cards_changed, error
  FROM scryfall_syncs
 WHERE finished_at IS NOT NULL AND error IS NULL
 ORDER BY finished_at DESC
 LIMIT 1
`

// The most recent import that finished without an error (including ones that found the
// bulk file unchanged and imported nothing).
func (q *Queries) LastSuccessfulSync(ctx context.Context) (ScryfallSync, error) {
	row := q.db.QueryRow(ctx, lastSuccessfulSync)
	var i ScryfallSync
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.BulkUpdatedAt,
		&i.SetsSeen,
		&i.CardsSeen,
		&i.CardsSkipped,
		&i.CardsChanged,
		&i.Error,
	)
	return i, err
}

const mergeStagedCards = `-- name: MergeStagedCards :execrows
INSERT INTO cards (
    id, oracle_id, name, lang, set_code, collector_number, rarity, layout, mana_cost, cmc,
    type_line, oracle_text, colors, color_identity, finishes, images, faces,
    price_eur, price_eur_foil, price_usd, price_usd_foil, price_usd_etched,
    cardmarket_id, cardmarket_url, released_at
)
SELECT DISTINCT ON (id)
    id, oracle_id, name, lang, set_code, collector_number, rarity, layout, mana_cost, cmc,
    type_line, oracle_text, colors, color_identity, finishes, images, faces,
    price_eur, price_eur_foil, price_usd, price_usd_foil, price_usd_etched,
    cardmarket_id, cardmarket_url, released_at
  FROM cards_staging
 ORDER BY id
ON CONFLICT (id) DO UPDATE
   SET oracle_id        = EXCLUDED.oracle_id,
       name             = EXCLUDED.name,
       lang             = EXCLUDED.lang,
       set_code         = EXCLUDED.set_code,
       collector_number = EXCLUDED.collector_number,
       rarity           = EXCLUDED.rarity,
       layout           = EXCLUDED.layout,
       mana_cost        = EXCLUDED.mana_cost,
       cmc              = EXCLUDED.cmc,
       type_line        = EXCLUDED.type_line,
       oracle_text      = EXCLUDED.oracle_text,
       colors           = EXCLUDED.colors,
       color_identity   = EXCLUDED.color_identity,
       finishes         = EXCLUDED.finishes,
       images           = EXCLUDED.images,
       faces            = EXCLUDED.faces,
       price_eur        = EXCLUDED.price_eur,
       price_eur_foil   = EXCLUDED.price_eur_foil,
       price_usd        = EXCLUDED.price_usd,
       price_usd_foil   = EXCLUDED.price_usd_foil,
       price_usd_etched = EXCLUDED.price_usd_etched,
       cardmarket_id    = EXCLUDED.cardmarket_id,
       cardmarket_url   = EXCLUDED.cardmarket_url,
       released_at      = EXCLUDED.released_at,
       updated_at       = now()
 WHERE (cards.oracle_id, cards.name, cards.lang, cards.set_code, cards.collector_number, cards.rarity,
        cards.layout, cards.mana_cost, cards.cmc, cards.type_line, cards.oracle_text, cards.colors,
        cards.color_identity, cards.finishes, cards.images, cards.faces, cards.price_eur,
        cards.price_eur_foil, cards.price_usd, cards.price_usd_foil, cards.price_usd_etched,
        cards.cardmarket_id, cards.cardmarket_url, cards.released_at)
       IS DISTINCT FROM
       (EXCLUDED.oracle_id, EXCLUDED.name, EXCLUDED.lang, EXCLUDED.set_code, EXCLUDED.collector_number,
        EXCLUDED.rarity, EXCLUDED.layout, EXCLUDED.mana_cost, EXCLUDED.cmc, EXCLUDED.type_line,
        EXCLUDED.oracle_text, EXCLUDED.colors, EXCLUDED.color_identity, EXCLUDED.finishes,
        EXCLUDED.images, EXCLUDED.faces, EXCLUDED.price_eur, EXCLUDED.price_eur_foil, EXCLUDED.price_usd,
        EXCLUDED.price_usd_foil, EXCLUDED.price_usd_etched, EXCLUDED.cardmarket_id,
        EXCLUDED.cardmarket_url, EXCLUDED.released_at)
`

// Moves the staged cards into cards: new ones are inserted, and existing ones are updated
// only if something changed, so a daily import rewrites just the cards whose prices moved.
// Returns how many cards were inserted or updated.
func (q *Queries) MergeStagedCards(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, mergeStagedCards)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

type StageCardsParams struct {
	ID              pgtype.UUID
	OracleID        pgtype.UUID
	Name            string
	Lang            string
	SetCode         string
	CollectorNumber string
	Rarity          string
	Layout          string
	ManaCost        string
	Cmc             pgtype.Numeric
	TypeLine        string
	OracleText      pgtype.Text
	Colors          []string
	ColorIdentity   []string
	Finishes        []string
	Images          []byte
	Faces           []byte
	PriceEur        pgtype.Numeric
	PriceEurFoil    pgtype.Numeric
	PriceUsd        pgtype.Numeric
	PriceUsdFoil    pgtype.Numeric
	PriceUsdEtched  pgtype.Numeric
	CardmarketID    pgtype.Int4
	CardmarketUrl   pgtype.Text
	ReleasedAt      pgtype.Date
}

const startSync = `-- name: StartSync :one
INSERT INTO scryfall_syncs DEFAULT VALUES
RETURNING id
`

func (q *Queries) StartSync(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, startSync)
	var id int64
	err := row.Scan(&id)
	return id, err
}
