// Code generated by tygo. DO NOT EDIT.
// The JSON shapes the API sends and receives, generated from the Go structs in
// backend/internal/contract. Edit those, then run `go generate ./...` in backend/.

//////////
// source: contract.go

export const FinishNonfoil = "nonfoil";
export const FinishFoil = "foil";
export const FinishEtched = "etched";
export type Finish = typeof FinishNonfoil | typeof FinishFoil | typeof FinishEtched;
/**
 * Cardmarket grading scale, best to worst.
 */
export const ConditionMT = "MT";
export const ConditionNM = "NM";
export const ConditionEX = "EX";
export const ConditionGD = "GD";
export const ConditionLP = "LP";
export const ConditionPL = "PL";
export const ConditionPO = "PO";
export type Condition = typeof ConditionMT | typeof ConditionNM | typeof ConditionEX | typeof ConditionGD | typeof ConditionLP | typeof ConditionPL | typeof ConditionPO;
export const RarityCommon = "common";
export const RarityUncommon = "uncommon";
export const RarityRare = "rare";
export const RarityMythic = "mythic";
export const RaritySpecial = "special";
export const RarityBonus = "bonus";
export type Rarity = typeof RarityCommon | typeof RarityUncommon | typeof RarityRare | typeof RarityMythic | typeof RaritySpecial | typeof RarityBonus;
export const ImageSizeSmall = "small";
export const ImageSizeNormal = "normal";
export const ImageSizeLarge = "large";
export const ImageSizeArtCrop = "art_crop";
export type ImageSize = typeof ImageSizeSmall | typeof ImageSizeNormal | typeof ImageSizeLarge | typeof ImageSizeArtCrop;
/**
 * Scryfall image URLs, one per ImageSize.
 */
export interface CardImages {
  small: string;
  normal: string;
  large: string;
  art_crop: string;
}
export interface CardFace {
  name: string;
  mana_cost: string;
  type_line: string;
  oracle_text?: string;
  /**
   * Only set for cards whose faces are printed on separate sides (transform, modal DFC, reversible).
   */
  images: CardImages | null;
}
/**
 * Scryfall's prices. EUR comes from Cardmarket. Scryfall has no EUR etched price:
 * etched copies use the EUR foil price when the printing has one, and etched-only
 * printings usually have no EUR price at all (so they count as unpriced).
 */
export interface Prices {
  eur: number | null;
  eur_foil: number | null;
  usd: number | null;
  usd_foil: number | null;
  usd_etched: number | null;
}
/**
 * The fields list views need (search results, collection entries).
 */
export interface CardSummary {
  id: string;
  oracle_id: string;
  name: string;
  set_code: string;
  set_name: string;
  collector_number: string;
  rarity: Rarity;
  /**
   * Scryfall language code of this printing, e.g. "en", "ja".
   */
  lang: string;
  mana_cost: string;
  cmc: number /* float64 */;
  type_line: string;
  colors: string[];
  color_identity: string[];
  /**
   * Front image; for double-faced cards this is the first face.
   */
  images: CardImages | null;
  prices: Prices;
  /**
   * Finishes this printing exists in.
   */
  finishes: Finish[];
  released_at: string;
}
/**
 * One Scryfall printing with everything the detail view shows.
 */
export interface Card extends CardSummary {
  faces: CardFace[] | null;
  oracle_text: string | null;
  cardmarket_url: string | null;
}
/**
 * A card the user owns: one printing in one finish, condition and language.
 */
export interface CollectionEntry {
  id: number /* int64 */;
  card: CardSummary;
  quantity: number /* int */;
  finish: Finish;
  condition: Condition;
  language: string;
  added_at: string;
  /**
   * EUR price of one copy in this finish, set by the server; null when there's no price.
   */
  unit_price_eur: number | null;
  /**
   * quantity × unit_price_eur; null when there's no price.
   */
  value_eur: number | null;
}
/**
 * A total over many cards, some of which may have no price.
 */
export interface ValueTotal {
  /**
   * Number of cards (copies) counted.
   */
  card_count: number /* int */;
  /**
   * Sum over the priced cards only.
   */
  value_eur: number /* float64 */;
  /**
   * How many of the cards had no EUR price and are left out of value_eur.
   */
  unpriced_count: number /* int */;
}
export const GroupByNone = "none";
export const GroupBySet = "set";
export const GroupByColor = "color";
export const GroupByType = "type";
export const GroupByRarity = "rarity";
export const GroupByCMC = "cmc";
export type GroupBy = typeof GroupByNone | typeof GroupBySet | typeof GroupByColor | typeof GroupByType | typeof GroupByRarity | typeof GroupByCMC;
export const SortByName = "name";
export const SortByPrice = "price";
export const SortByCMC = "cmc";
export const SortByAdded = "added";
export type SortBy = typeof SortByName | typeof SortByPrice | typeof SortByCMC | typeof SortByAdded;
/**
 * The header of one auto-group (e.g. "Red", "Modern Horizons 2"). Its entries
 * are fetched separately, a page at a time, as an EntryPage.
 */
export interface GroupSummary extends ValueTotal {
  key: string;
  label: string;
  /**
   * Number of collection entries (distinct printing/finish/condition/language rows).
   */
  entry_count: number /* int */;
}
/**
 * One page of collection entries; pass next_cursor back to get the next page.
 */
export interface EntryPage {
  entries: CollectionEntry[];
  next_cursor: string | null;
}
/**
 * A collection entry as a member of a custom group. A binder can hold only some
 * of an entry's copies, so the member has its own quantity and value.
 */
export interface GroupMember {
  entry: CollectionEntry;
  /**
   * Copies of the entry in this group: 1 to entry.quantity.
   */
  quantity: number /* int */;
  /**
   * quantity × entry.unit_price_eur; null when there's no price.
   */
  value_eur: number | null;
}
/**
 * One page of a custom group's members.
 */
export interface GroupMemberPage {
  members: GroupMember[];
  next_cursor: string | null;
}
export const CustomGroupKindBinder = "binder";
export const CustomGroupKindDeck = "deck";
export const CustomGroupKindBox = "box";
export const CustomGroupKindOther = "other";
export type CustomGroupKind = typeof CustomGroupKindBinder | typeof CustomGroupKindDeck | typeof CustomGroupKindBox | typeof CustomGroupKindOther;
/**
 * A user-created group of cards: a binder, deck, box, etc.
 */
export interface CustomGroup extends ValueTotal {
  id: number /* int64 */;
  name: string;
  kind: CustomGroupKind;
  description: string;
  preview_images: string[];
}
/**
 * Totals for the whole collection. Values are EUR only: Cardmarket is the reference market.
 */
export interface CollectionStats extends ValueTotal {
  /**
   * Distinct printings owned (entries for the same printing in other finishes/conditions count once).
   */
  unique_cards: number /* int */;
  by_color: { [key: string]: number /* int */};
  by_rarity: { [R in Rarity]?: number };
}
export const HealthStatusOK = "ok";
export const HealthStatusUnavailable = "unavailable";
export type HealthStatus = typeof HealthStatusOK | typeof HealthStatusUnavailable;
/**
 * GET /api/health: whether the server can reach its database.
 */
export interface Health {
  status: HealthStatus;
}
/**
 * What the add-to-collection form submits.
 */
export interface NewEntry {
  card_id: string;
  quantity: number /* int */;
  finish: Finish;
  condition: Condition;
  language: string;
  group_id: number | null;
}
